root = "."
testdata_dir = "testdata"

[build]
  args_bin = ["-d", "serve"]
  bin = "./dist/craig-stars"
  cmd = "go build -buildvcs=false -o ./dist/craig-stars ."
  delay = 1000
  exclude_dir = ["dist", "frontend", "vendor", "testdata", "data"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl"]
  kill_delay = ".5s"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
