import type { Cost } from './Cost';
import type { TechLevels as TechLevel } from './Player';

export interface TechStore {
	engines: TechEngine[];
	planetaryScanners: TechPlanetaryScanner[];
	defenses: TechDefense[];
	hullComponents: TechHullComponent[];
}

export interface Tech {
	id: number;
	createdAt: string;
	updatedat: string;
	deletedAt: null;
	techStoreId: number;
	name: string;
	cost: Cost;
	requirements: TechRequirements;
	ranking?: number;
	category: TechCategory;
}

export interface TechPlanetaryScanner extends Tech {
	scanRange: number;
	scanRangePen?: number;
}

// Generated by https://quicktype.io

export interface TechDefense extends Tech {
	defenseCoverage: number;
}

export interface TechHullComponent extends Tech {
	hullSlotType: HullSlotType;
	scanRange: number;
	scanRangePen: number;
	safeHullMass: number;
	safeRange: number;
	maxHullMass: number;
	maxRange: number;
	ranking?: number;
	packetSpeed?: number;
	mass?: number;
	miningRate?: number;
	cloakUnits?: number;
	terraformRate?: number;
	killRate?: number;
	minKillRate?: number;
	structureDestroyRate?: number;
	unterraformRate?: number;
	smart?: boolean;
	canStealFleetCargo?: boolean;
	canStealPlanetCargo?: boolean;
	armor?: number;
	shield?: number;
	cloakUnarmedOnly?: boolean;
	torpedoBonus?: number;
	initiativeBonus?: number;
	torpedoJamming?: number;
	beamBonus?: number;
	reduceMovement?: number;
	reduceCloaking?: boolean;
	fuelBonus?: number;
	fuelRegenerationRate?: number;
	mineFieldType?: MineFieldType;
	mineLayingRate?: number;
	colonizationModule?: boolean;
	orbitalConstructionModule?: boolean;
	cargoBonus?: number;
	movementBonus?: number;
	beamDefense?: number;
	power?: number;
	range?: number;
	initiative?: number;
	gattling?: boolean;
	hitsAllTargets?: boolean;
	damageShieldsOnly?: boolean;
	accuracy?: number;
	capitalShipMissile?: boolean;
}

export enum HullSlotType {
	Armor = 'Armor',
	BeamWeapon = 'BeamWeapon',
	Bomb = 'Bomb',
	Electrical = 'Electrical',
	Mechanical = 'Mechanical',
	MineLayer = 'MineLayer',
	MineRobot = 'MineRobot',
	Mining = 'Mining',
	Orbital = 'Orbital',
	Scanner = 'Scanner',
	Shield = 'Shield',
	Torpedo = 'Torpedo',
	Weapon = 'Weapon'
}

export enum MineFieldType {
	Heavy = 'Heavy',
	SpeedBump = 'SpeedBump',
	Standard = 'Standard'
}

export interface TechEngine extends TechHullComponent {
	idealSpeed?: number;
	freeSpeed?: number;
	fuelUsage?: number[];
}

export enum TechCategory {
	Armor = 'Armor',
	BeamWeapon = 'BeamWeapon',
	Bomb = 'Bomb',
	Electrical = 'Electrical',
	Engine = 'Engine',
	Mechanical = 'Mechanical',
	MineLayer = 'MineLayer',
	MineRobot = 'MineRobot',
	Orbital = 'Orbital',
	PlanetaryScanner = 'PlanetaryScanner',
	PlanetaryDefense = 'PlanetaryDefense',
	Scanner = 'Scanner',
	Shield = 'Shield',
	ShipHull = 'ShipHull',
	StarbaseHull = 'StarbaseHull',
	Terraforming = 'Terraforming',
	Torpedo = 'Torpedo'
}

export interface TechRequirements extends TechLevel {
	lrtsRequired: number[] | null;
	lrtsDenied: number[] | null;
	prtRequired?: string;
	prtDenied?: string;
}
