CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  username TEXT UNIQUE NOT NULL,
  password TEXT,
  email TEXT,
  verified NUMERIC,
  banned NUMERIC,
  role TEXT NOT NULL,
  lastLogin TIMESTAMP,
  discordId TEXT,
  discordAvatar TEXT,
  discordWebhookUrl TEXT DEFAULT '',
  gameId INTEGER NOT NULL DEFAULT 0,
  playerNum INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE races (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  userId INTEGER NOT NULL,
  name TEXT NOT NULL,
  pluralName TEXT NOT NULL,
  spendLeftoverPointsOn TEXT NOT NULL,
  prt TEXT,
  lrts INTEGER,
  habLowGrav INTEGER,
  habLowTemp INTEGER,
  habLowRad INTEGER,
  habHighGrav INTEGER,
  habHighTemp INTEGER,
  habHighRad INTEGER,
  growthRate INTEGER,
  popEfficiency INTEGER,
  factoryOutput INTEGER,
  factoryCost INTEGER,
  numFactories INTEGER,
  factoriesCostLess NUMERIC,
  immuneGrav NUMERIC,
  immuneTemp NUMERIC,
  immuneRad NUMERIC,
  mineOutput INTEGER,
  mineCost INTEGER,
  numMines INTEGER,
  researchCostEnergy TEXT,
  researchCostWeapons TEXT,
  researchCostPropulsion TEXT,
  researchCostConstruction TEXT,
  researchCostElectronics TEXT,
  researchCostBiotechnology TEXT,
  techsStartHigh NUMERIC,
  spec TEXT,
  CONSTRAINT fkUsersRaces FOREIGN KEY (userId) REFERENCES users (id) ON DELETE CASCADE
);
CREATE TABLE games (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  hostId INTEGER,
  name TEXT NOT NULL,
  state TEXT,
  public NUMERIC,
  hash TEXT,
  size TEXT,
  density TEXT,
  playerPositions TEXT,
  randomEvents NUMERIC,
  computerPlayersFormAlliances NUMERIC,
  publicPlayerScores NUMERIC,
  startMode TEXT,
  quickStartTurns INTEGER,
  openPlayerSlots INTEGER,
  numPlayers INTEGER,
  victoryConditionsConditions INTEGER,
  victoryConditionsNumCriteriaRequired INTEGER,
  victoryConditionsYearsPassed INTEGER,
  victoryConditionsOwnPlanets INTEGER,
  victoryConditionsAttainTechLevel INTEGER,
  victoryConditionsAttainTechLevelNumFields INTEGER,
  victoryConditionsExceedsScore INTEGER,
  victoryConditionsExceedsSecondPlaceScore INTEGER,
  victoryConditionsProductionCapacity INTEGER,
  victoryConditionsOwnCapitalShips INTEGER,
  victoryConditionsHighestScoreAfterYears INTEGER,
  seed INTEGER,
  rules TEXT,
  areaX REAL,
  areaY REAL,
  year INTEGER,
  victorDeclared NUMERIC,
  maxMinerals NUMERIC DEFAULT 0,
  archived NUMERIC NOT NULL default 0
);
CREATE TABLE rules (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  gameId INTEGER NOT NULL,
  seed INTEGER,
  tachyonCloakReduction INTEGER,
  maxPopulation INTEGER,
  fleetsScanWhileMoving NUMERIC,
  populationScannerError REAL,
  smartDefenseCoverageFactor REAL,
  invasionDefenseCoverageFactor REAL,
  numBattleRounds INTEGER,
  movesToRunAway INTEGER,
  beamRangeDropoff REAL,
  torpedoSplashDamage REAL,
  salvageDecayRate REAL,
  salvageDecayMin INTEGER,
  mineFieldCloak INTEGER,
  stargateMaxRangeFactor INTEGER,
  stargateMaxHullMassFactor INTEGER,
  randomEventChances TEXT,
  randomMineralDepositBonusRange TEXT,
  wormholeCloak INTEGER,
  wormholeMinDistance INTEGER,
  wormholeStatsByStability TEXT,
  wormholePairsForSize TEXT,
  mineFieldStatsByType TEXT,
  repairRates TEXT,
  maxPlayers INTEGER,
  startingYear INTEGER,
  showPublicScoresAfterYears INTEGER,
  planetMinDistance INTEGER,
  maxExtraWorldDistance INTEGER,
  minExtraWorldDistance INTEGER,
  minHomeworldMineralConcentration INTEGER,
  minExtraPlanetMineralConcentration INTEGER,
  minMineralConcentration INTEGER,
  minStartingMineralConcentration INTEGER,
  maxStartingMineralConcentration INTEGER,
  highRadGermaniumBonus INTEGER,
  highRadGermaniumBonusThreshold INTEGER,
  maxStartingMineralSurface INTEGER,
  minStartingMineralSurface INTEGER,
  mineralDecayFactor INTEGER,
  startingMines INTEGER,
  startingFactories INTEGER,
  startingDefenses INTEGER,
  raceStartingPoints INTEGER,
  scrapMineralAmount REAL,
  scrapResourceAmount REAL,
  factoryCostGermanium INTEGER,
  defenseCost TEXT,
  mineralAlchemyCost INTEGER,
  terraformCost TEXT,
  starbaseComponentCostFactor REAL,
  packetDecayRate TEXT,
  maxTechLevel INTEGER,
  techBaseCost TEXT,
  prtSpecs TEXT,
  lrtSpecs TEXT,
  techsId INTEGER
);
CREATE TABLE players (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  gameId INTEGER NOT NULL,
  userId INTEGER,
  name TEXT NOT NULL,
  num INTEGER NOT NULL,
  ready NUMERIC,
  aiControlled NUMERIC,
  submittedTurn NUMERIC,
  color TEXT,
  defaultHullSet INTEGER,
  techLevelsEnergy INTEGER,
  techLevelsWeapons INTEGER,
  techLevelsPropulsion INTEGER,
  techLevelsConstruction INTEGER,
  techLevelsElectronics INTEGER,
  techLevelsBiotechnology INTEGER,
  techLevelsSpentEnergy INTEGER,
  techLevelsSpentWeapons INTEGER,
  techLevelsSpentPropulsion INTEGER,
  techLevelsSpentConstruction INTEGER,
  techLevelsSpentElectronics INTEGER,
  techLevelsSpentBiotechnology INTEGER,
  researchAmount INTEGER,
  researchSpentLastYear INTEGER,
  nextResearchField TEXT,
  researching TEXT,
  battlePlans TEXT,
  productionPlans TEXT,
  transportPlans TEXT,
  relations TEXT,
  cargoTransfers TEXT,
  messages TEXT,
  battleRecords TEXT,
  playerIntels TEXT,
  scoreIntels TEXT,
  planetIntels TEXT,
  fleetIntels TEXT,
  shipDesignIntels TEXT,
  mineralPacketIntels TEXT,
  mineFieldIntels TEXT,
  wormholeIntels TEXT,
  mysteryTraderIntels TEXT,
  salvageIntels TEXT,
  race TEXT,
  stats TEXT,
  scoreHistory TEXT,
  achievedVictoryConditions INTEGER,
  victor NUMERIC,
  spec TEXT,
  guest NUMERIC NOT NULL default 0,
  aiDifficulty TEXT DEFAULT "",
  acquiredTechs TEXT,
  archived NUMERIC NOT NULL default 0,
  UNIQUE (gameId, num),
  CONSTRAINT fkGamesPlayers FOREIGN KEY (gameId) REFERENCES games (id) ON DELETE CASCADE
);
CREATE TABLE fleets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  gameId INTEGER NOT NULL,
  battlePlanNum INTEGER NOT NULL,
  x REAL,
  y REAL,
  name TEXT NOT NULL,
  num INTEGER,
  playerNum INTEGER,
  tokens TEXT,
  waypoints TEXT,
  repeatOrders NUMERIC,
  planetNum INTEGER,
  baseName TEXT NOT NULL,
  ironium INTEGER,
  boranium INTEGER,
  germanium INTEGER,
  colonists INTEGER,
  fuel INTEGER,
  age INTEGER,
  headingX REAL,
  headingY REAL,
  warpSpeed INTEGER,
  previousPositionX REAL,
  previousPositionY REAL,
  orbitingPlanetNum INTEGER,
  starbase NUMERIC,
  spec TEXT,
  purpose TEXT NOT NULL default '',
  tags TEXT,
  CONSTRAINT fkPlayersFleets FOREIGN KEY (gameId, playerNum) REFERENCES players (gameId, num) ON DELETE CASCADE,
  CONSTRAINT fkGamesFleets FOREIGN KEY (gameId) REFERENCES games (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX fleetNum on fleets(gameId, playerNum, num)
WHERE starbase = 0;
CREATE TABLE shipDesigns (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  gameId INTEGER NOT NULL,
  num INTEGER NOT NULL,
  playerNum INTEGER NOT NULL,
  name TEXT NOT NULL,
  version INTEGER,
  hull TEXT,
  hullSetNumber INTEGER,
  canDelete NUMERIC,
  slots TEXT,
  purpose TEXT,
  spec TEXT,
  cannotDelete NUMERIC NOT NULL default 0,
  originalPlayerNum INTEGER DEFAULT 0,
  mysteryTrader NUMERIC,
  UNIQUE (gameId, playerNum, num),
  UNIQUE (gameId, playerNum, name),
  CONSTRAINT fkPlayersDesigns FOREIGN KEY (gameId, playerNum) REFERENCES players (gameId, num) ON DELETE CASCADE
);
CREATE TABLE planets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  gameId INTEGER NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  x REAL,
  y REAL,
  name TEXT NOT NULL,
  num INTEGER,
  playerNum INTEGER,
  grav INTEGER,
  temp INTEGER,
  rad INTEGER,
  baseGrav INTEGER,
  baseTemp INTEGER,
  baseRad INTEGER,
  terraformedAmountGrav INTEGER,
  terraformedAmountTemp INTEGER,
  terraformedAmountRad INTEGER,
  mineralConcIronium INTEGER,
  mineralConcBoranium INTEGER,
  mineralConcGermanium INTEGER,
  mineYearsIronium INTEGER,
  mineYearsBoranium INTEGER,
  mineYearsGermanium INTEGER,
  ironium INTEGER,
  boranium INTEGER,
  germanium INTEGER,
  colonists INTEGER,
  partialPopulation INTEGER,
  mines INTEGER,
  factories INTEGER,
  defenses INTEGER,
  homeworld NUMERIC,
  contributesOnlyLeftoverToResearch NUMERIC,
  scanner NUMERIC,
  routeTargetType TEXT,
  routeTargetNum INTEGER,
  routeTargetPlayerNum INTEGER,
  packetTargetNum INTEGER,
  packetSpeed INTEGER,
  productionQueue TEXT,
  spec TEXT,
  tags TEXT,
  randomArtifact NUMERIC DEFAULT 0,
  UNIQUE (gameId, num),
  CONSTRAINT fkGamesPlanets FOREIGN KEY (gameId) REFERENCES games (id) ON DELETE CASCADE
);
CREATE TABLE mineralPackets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  gameId INTEGER NOT NULL,
  x REAL,
  y REAL,
  name TEXT NOT NULL,
  num INTEGER,
  playerNum INTEGER,
  targetPlanetNum INTEGER,
  ironium INTEGER,
  boranium INTEGER,
  germanium INTEGER,
  safeWarpSpeed INTEGER,
  warpSpeed INTEGER,
  scanRange INTEGER,
  scanRangePen INTEGER,
  headingX REAL,
  headingY REAL,
  tags TEXT,
  UNIQUE (gameId, playerNum, num),
  CONSTRAINT fkPlayersMineralPackets FOREIGN KEY (gameId, playerNum) REFERENCES players (gameId, num),
  CONSTRAINT fkGamesMineralPackets FOREIGN KEY (gameId) REFERENCES games (id) ON DELETE CASCADE
);
CREATE TABLE salvages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  gameId INTEGER NOT NULL,
  x REAL,
  y REAL,
  name TEXT NOT NULL,
  num INTEGER,
  playerNum INTEGER,
  ironium INTEGER,
  boranium INTEGER,
  germanium INTEGER,
  tags TEXT,
  UNIQUE (gameId, num),
  CONSTRAINT fkPlayersSalvages FOREIGN KEY (gameId, playerNum) REFERENCES players (gameId, num),
  CONSTRAINT fkGamesSalvages FOREIGN KEY (gameId) REFERENCES games (id) ON DELETE CASCADE
);
CREATE TABLE wormholes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  gameId INTEGER NOT NULL,
  x REAL,
  y REAL,
  name TEXT NOT NULL,
  num INTEGER,
  destinationNum INTEGER,
  stability TEXT,
  yearsAtStability INTEGER,
  spec TEXT,
  tags TEXT,
  UNIQUE (gameId, num),
  CONSTRAINT fkGamesWormholes FOREIGN KEY (gameId) REFERENCES games (id) ON DELETE CASCADE
);
CREATE TABLE mysteryTraders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  gameId INTEGER NOT NULL,
  x REAL,
  y REAL,
  name TEXT NOT NULL,
  num INTEGER,
  headingX REAL,
  headingY REAL,
  warpSpeed INTEGER,
  spec TEXT,
  tags TEXT,
  requestedBoon INTEGER,
  destinationX REAL,
  destinationY REAL,
  rewardType TEXT,
  playersRewarded TEXT,
  UNIQUE (gameId, num),
  CONSTRAINT fkGamesMysteryTraders FOREIGN KEY (gameId) REFERENCES games (id) ON DELETE CASCADE
);
CREATE TABLE mineFields (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  gameId INTEGER NOT NULL,
  x REAL,
  y REAL,
  name TEXT NOT NULL,
  num INTEGER,
  playerNum INTEGER,
  numMines INTEGER,
  detonate NUMERIC,
  mineFieldType TEXT,
  spec TEXT,
  tags TEXT,
  UNIQUE (gameId, playerNum, num),
  CONSTRAINT fkPlayersMineFields FOREIGN KEY (gameId, playerNum) REFERENCES players (gameId, num),
  CONSTRAINT fkGamesMineFields FOREIGN KEY (gameId) REFERENCES games (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX fleetStarbasePlanet on fleets(gameId, playerNum, planetNum)
WHERE starbase = 1;
CREATE TABLE versions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  current NUMERIC
);
INSERT INTO versions (current)
VALUES (0);