CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  username TEXT UNIQUE NOT NULL,
  password TEXT,
  email TEXT,
  verified BOOLEAN,
  banned BOOLEAN,
  role TEXT NOT NULL,
  lastLogin TIMESTAMP,
  discordId TEXT,
  discordAvatar TEXT,
  discordWebhookUrl TEXT DEFAULT '',
  gameId INTEGER NOT NULL DEFAULT 0,
  playerNum INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE races (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  userId INTEGER NOT NULL,
  name TEXT NOT NULL,
  pluralName TEXT NOT NULL,
  spendLeftoverPointsOn TEXT NOT NULL,
  prt TEXT,
  lrts INTEGER,
  habLowGrav INTEGER,
  habLowTemp INTEGER,
  habLowRad INTEGER,
  habHighGrav INTEGER,
  habHighTemp INTEGER,
  habHighRad INTEGER,
  growthRate INTEGER,
  popEfficiency INTEGER,
  factoryOutput INTEGER,
  factoryCost INTEGER,
  numFactories INTEGER,
  factoriesCostLess BOOLEAN,
  immuneGrav BOOLEAN,
  immuneTemp BOOLEAN,
  immuneRad BOOLEAN,
  mineOutput INTEGER,
  mineCost INTEGER,
  numMines INTEGER,
  researchCostEnergy TEXT,
  researchCostWeapons TEXT,
  researchCostPropulsion TEXT,
  researchCostConstruction TEXT,
  researchCostElectronics TEXT,
  researchCostBiotechnology TEXT,
  techsStartHigh BOOLEAN,
  spec TEXT,
  CONSTRAINT fkUsersRaces FOREIGN KEY (userId) REFERENCES users (id) ON DELETE CASCADE
);
CREATE TABLE games (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  hostId INTEGER,
  name TEXT NOT NULL,
  state TEXT,
  public BOOLEAN,
  hash TEXT,
  size TEXT,
  density TEXT,
  playerPositions TEXT,
  randomEvents BOOLEAN,
  computerPlayersFormAlliances BOOLEAN,
  publicPlayerScores BOOLEAN,
  startMode TEXT,
  quickStartTurns INTEGER,
  openPlayerSlots INTEGER,
  numPlayers INTEGER,
  victoryConditionsConditions INTEGER,
  victoryConditionsNumCriteriaRequired INTEGER,
  victoryConditionsYearsPassed INTEGER,
  victoryConditionsOwnPlanets INTEGER,
  victoryConditionsAttainTechLevel INTEGER,
  victoryConditionsAttainTechLevelNumFields INTEGER,
  victoryConditionsExceedsScore INTEGER,
  victoryConditionsExceedsSecondPlaceScore INTEGER,
  victoryConditionsProductionCapacity INTEGER,
  victoryConditionsOwnCapitalShips INTEGER,
  victoryConditionsHighestScoreAfterYears INTEGER,
  seed INTEGER,
  areaX REAL,
  areaY REAL,
  year INTEGER,
  victorDeclared BOOLEAN,
  maxMinerals BOOLEAN DEFAULT 0,
  archived BOOLEAN NOT NULL default 0
);

CREATE TABLE players (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gameId INTEGER NOT NULL,
  userId INTEGER,
  name TEXT NOT NULL,
  num INTEGER NOT NULL,
  ready BOOLEAN,
  aiControlled BOOLEAN,
  submittedTurn BOOLEAN,
  color TEXT,
  defaultHullSet INTEGER,
  techLevelsEnergy INTEGER,
  techLevelsWeapons INTEGER,
  techLevelsPropulsion INTEGER,
  techLevelsConstruction INTEGER,
  techLevelsElectronics INTEGER,
  techLevelsBiotechnology INTEGER,
  techLevelsSpentEnergy INTEGER,
  techLevelsSpentWeapons INTEGER,
  techLevelsSpentPropulsion INTEGER,
  techLevelsSpentConstruction INTEGER,
  techLevelsSpentElectronics INTEGER,
  techLevelsSpentBiotechnology INTEGER,
  researchAmount INTEGER,
  researchSpentLastYear INTEGER,
  nextResearchField TEXT,
  researching TEXT,
  battlePlans TEXT,
  productionPlans TEXT,
  transportPlans TEXT,
  relations TEXT,
  cargoTransfers TEXT,
  messages TEXT,
  battleRecords TEXT,
  playerIntels TEXT,
  scoreIntels TEXT,
  planetIntels TEXT,
  fleetIntels TEXT,
  shipDesignIntels TEXT,
  mineralPacketIntels TEXT,
  mineFieldIntels TEXT,
  wormholeIntels TEXT,
  mysteryTraderIntels TEXT,
  salvageIntels TEXT,
  race TEXT,
  stats TEXT,
  scoreHistory TEXT,
  achievedVictoryConditions INTEGER,
  victor BOOLEAN,
  spec TEXT,
  guest BOOLEAN NOT NULL default 0,
  aiDifficulty TEXT DEFAULT "",
  acquiredTechs TEXT,
  archived BOOLEAN NOT NULL default 0,
  UNIQUE (gameId, num),
  CONSTRAINT fkGamesPlayers FOREIGN KEY (gameId) REFERENCES games (id) ON DELETE CASCADE
);
CREATE TABLE fleets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gameId INTEGER NOT NULL,
  battlePlanNum INTEGER NOT NULL,
  x REAL,
  y REAL,
  name TEXT NOT NULL,
  num INTEGER,
  playerNum INTEGER,
  tokens TEXT,
  waypoints TEXT,
  repeatOrders BOOLEAN,
  planetNum INTEGER,
  baseName TEXT NOT NULL,
  ironium INTEGER,
  boranium INTEGER,
  germanium INTEGER,
  colonists INTEGER,
  fuel INTEGER,
  age INTEGER,
  headingX REAL,
  headingY REAL,
  warpSpeed INTEGER,
  previousPositionX REAL,
  previousPositionY REAL,
  orbitingPlanetNum INTEGER,
  starbase BOOLEAN,
  spec TEXT,
  purpose TEXT NOT NULL default '',
  tags TEXT,
  CONSTRAINT fkPlayersFleets FOREIGN KEY (gameId, playerNum) REFERENCES players (gameId, num) ON DELETE CASCADE,
  CONSTRAINT fkGamesFleets FOREIGN KEY (gameId) REFERENCES games (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX fleetNum on fleets(gameId, playerNum, num)
WHERE starbase = 0;
CREATE TABLE shipDesigns (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gameId INTEGER NOT NULL,
  num INTEGER NOT NULL,
  playerNum INTEGER NOT NULL,
  name TEXT NOT NULL,
  version INTEGER,
  hull TEXT,
  hullSetNumber INTEGER,
  canDelete BOOLEAN,
  slots TEXT,
  purpose TEXT,
  spec TEXT,
  cannotDelete BOOLEAN NOT NULL default 0,
  originalPlayerNum INTEGER DEFAULT 0,
  mysteryTrader BOOLEAN,
  UNIQUE (gameId, playerNum, num),
  UNIQUE (gameId, playerNum, name),
  CONSTRAINT fkPlayersDesigns FOREIGN KEY (gameId, playerNum) REFERENCES players (gameId, num) ON DELETE CASCADE
);
CREATE TABLE planets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  gameId INTEGER NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  x REAL,
  y REAL,
  name TEXT NOT NULL,
  num INTEGER,
  playerNum INTEGER,
  grav INTEGER,
  temp INTEGER,
  rad INTEGER,
  baseGrav INTEGER,
  baseTemp INTEGER,
  baseRad INTEGER,
  terraformedAmountGrav INTEGER,
  terraformedAmountTemp INTEGER,
  terraformedAmountRad INTEGER,
  mineralConcIronium INTEGER,
  mineralConcBoranium INTEGER,
  mineralConcGermanium INTEGER,
  mineYearsIronium INTEGER,
  mineYearsBoranium INTEGER,
  mineYearsGermanium INTEGER,
  ironium INTEGER,
  boranium INTEGER,
  germanium INTEGER,
  colonists INTEGER,
  partialPopulation INTEGER,
  mines INTEGER,
  factories INTEGER,
  defenses INTEGER,
  homeworld BOOLEAN,
  contributesOnlyLeftoverToResearch BOOLEAN,
  scanner BOOLEAN,
  routeTargetType TEXT,
  routeTargetNum INTEGER,
  routeTargetPlayerNum INTEGER,
  packetTargetNum INTEGER,
  packetSpeed INTEGER,
  productionQueue TEXT,
  spec TEXT,
  tags TEXT,
  randomArtifact BOOLEAN DEFAULT 0,
  UNIQUE (gameId, num),
  CONSTRAINT fkGamesPlanets FOREIGN KEY (gameId) REFERENCES games (id) ON DELETE CASCADE
);
CREATE TABLE mineralPackets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gameId INTEGER NOT NULL,
  x REAL,
  y REAL,
  name TEXT NOT NULL,
  num INTEGER,
  playerNum INTEGER,
  targetPlanetNum INTEGER,
  ironium INTEGER,
  boranium INTEGER,
  germanium INTEGER,
  safeWarpSpeed INTEGER,
  warpSpeed INTEGER,
  scanRange INTEGER,
  scanRangePen INTEGER,
  headingX REAL,
  headingY REAL,
  tags TEXT,
  UNIQUE (gameId, playerNum, num),
  CONSTRAINT fkPlayersMineralPackets FOREIGN KEY (gameId, playerNum) REFERENCES players (gameId, num),
  CONSTRAINT fkGamesMineralPackets FOREIGN KEY (gameId) REFERENCES games (id) ON DELETE CASCADE
);
CREATE TABLE salvages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gameId INTEGER NOT NULL,
  x REAL,
  y REAL,
  name TEXT NOT NULL,
  num INTEGER,
  playerNum INTEGER,
  ironium INTEGER,
  boranium INTEGER,
  germanium INTEGER,
  tags TEXT,
  UNIQUE (gameId, num),
  CONSTRAINT fkPlayersSalvages FOREIGN KEY (gameId, playerNum) REFERENCES players (gameId, num),
  CONSTRAINT fkGamesSalvages FOREIGN KEY (gameId) REFERENCES games (id) ON DELETE CASCADE
);
CREATE TABLE wormholes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gameId INTEGER NOT NULL,
  x REAL,
  y REAL,
  name TEXT NOT NULL,
  num INTEGER,
  destinationNum INTEGER,
  stability TEXT,
  yearsAtStability INTEGER,
  spec TEXT,
  tags TEXT,
  UNIQUE (gameId, num),
  CONSTRAINT fkGamesWormholes FOREIGN KEY (gameId) REFERENCES games (id) ON DELETE CASCADE
);
CREATE TABLE mysteryTraders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gameId INTEGER NOT NULL,
  x REAL,
  y REAL,
  name TEXT NOT NULL,
  num INTEGER,
  headingX REAL,
  headingY REAL,
  warpSpeed INTEGER,
  spec TEXT,
  tags TEXT,
  requestedBoon INTEGER,
  destinationX REAL,
  destinationY REAL,
  rewardType TEXT,
  playersRewarded TEXT,
  UNIQUE (gameId, num),
  CONSTRAINT fkGamesMysteryTraders FOREIGN KEY (gameId) REFERENCES games (id) ON DELETE CASCADE
);
CREATE TABLE mineFields (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gameId INTEGER NOT NULL,
  x REAL,
  y REAL,
  name TEXT NOT NULL,
  num INTEGER,
  playerNum INTEGER,
  numMines INTEGER,
  detonate BOOLEAN,
  mineFieldType TEXT,
  spec TEXT,
  tags TEXT,
  UNIQUE (gameId, playerNum, num),
  CONSTRAINT fkPlayersMineFields FOREIGN KEY (gameId, playerNum) REFERENCES players (gameId, num),
  CONSTRAINT fkGamesMineFields FOREIGN KEY (gameId) REFERENCES games (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX fleetStarbasePlanet on fleets(gameId, playerNum, planetNum)
WHERE starbase = 1;
CREATE TABLE versions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  current NUMERIC
);
INSERT INTO versions (current)
VALUES (0);

CREATE VIEW
  game_players AS
SELECT
  players.gameId,
  players.id,
  players.updatedAt,
  players.userId,
  players.name,
  players.num,
  players.ready,
  players.aiControlled,
  players.aiDifficulty,
  players.submittedTurn,
  players.color,
  players.victor,
  players.archived,
  players.guest
FROM
  players;

CREATE INDEX idx_games_hostid_gameid ON games(hostId);
CREATE INDEX idx_players_userid_gameid ON players(userId, gameId);
CREATE INDEX idx_players_gameid ON players(gameId);
CREATE INDEX idx_players_gameid_num ON players(gameId, num);
CREATE INDEX idx_planets_gameid ON planets(gameId);
CREATE INDEX idx_planets_gameid_player_num ON planets(gameId, playerNum);
CREATE INDEX idx_ship_designs_gameid ON shipDesigns(gameId);
CREATE INDEX idx_ship_designs_gameid_playernum ON shipDesigns(gameId, playerNum);
CREATE INDEX idx_fleets_gameid ON fleets(gameId);
CREATE INDEX idx_fleets_gameid_player_num ON fleets(gameId, playerNum);
CREATE INDEX idx_fleets_planet_num ON fleets(gameId, planetNum);
CREATE INDEX idx_salvages_gameid ON salvages(gameId);
CREATE INDEX idx_wormholes_gameid ON wormholes(gameId);
CREATE INDEX idx_minefields_gameid ON mineFields(gameId);
CREATE INDEX idx_mineral_packets_gameid ON mineralPackets(gameId);
CREATE INDEX idx_mystery_traders_gameid ON mysteryTraders(gameId);
