CREATE TABLE
  IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    username TEXT UNIQUE NOT NULL,
    password TEXT,
    email TEXT,
    verified BOOLEAN,
    banned BOOLEAN,
    role TEXT NOT NULL
  );

CREATE TABLE
  IF NOT EXISTS races (
    id INTEGER PRIMARY KEY,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    userId INTEGER NOT NULL,
    name TEXT NOT NULL,
    pluralName TEXT NOT NULL,
    spendLeftoverPointsOn TEXT NOT NULL,
    prt TEXT,
    lrts INTEGER,
    habLowGrav INTEGER,
    habLowTemp INTEGER,
    habLowRad INTEGER,
    habHighGrav INTEGER,
    habHighTemp INTEGER,
    habHighRad INTEGER,
    growthRate INTEGER,
    popEfficiency INTEGER,
    factoryOutput INTEGER,
    factoryCost INTEGER,
    numFactories INTEGER,
    factoriesCostLess BOOLEAN,
    immuneGrav BOOLEAN,
    immuneTemp BOOLEAN,
    immuneRad BOOLEAN,
    mineOutput INTEGER,
    mineCost INTEGER,
    numMines INTEGER,
    researchCostEnergy TEXT,
    researchCostWeapons TEXT,
    researchCostPropulsion TEXT,
    researchCostConstruction TEXT,
    researchCostElectronics TEXT,
    researchCostBiotechnology TEXT,
    techsStartHigh BOOLEAN,
    spec TEXT,
    CONSTRAINT fkUsersRaces FOREIGN KEY (userId) REFERENCES users (id) ON DELETE CASCADE
  );