CREATE TABLE users.users (
  id INTEGER PRIMARY KEY,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  username TEXT UNIQUE NOT NULL,
  discord TEXT,
  password TEXT,
  email TEXT,
  verified NUMERIC,
  banned NUMERIC,
  role TEXT NOT NULL
);
CREATE TABLE users.races (
  id INTEGER PRIMARY KEY,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENTTIMESTAMP,
  userId INTEGER NOT NULL,
  name TEXT NOT NULL,
  pluralName TEXT NOT NULL,
  spendLeftoverPointsOn TEXT NOT NULL,
  prt TEXT,
  lrts INTEGER,
  habLowGrav INTEGER,
  habLowTemp INTEGER,
  habLowRad INTEGER,
  habHighGrav INTEGER,
  habHighTemp INTEGER,
  habHighRad INTEGER,
  growthRate INTEGER,
  popEfficiency INTEGER,
  factoryOutput INTEGER,
  factoryCost INTEGER,
  numFactories INTEGER,
  factoriesCostLess NUMERIC,
  immuneGrav NUMERIC,
  immuneTemp NUMERIC,
  immuneRad NUMERIC,
  mineOutput INTEGER,
  mineCost INTEGER,
  numMines INTEGER,
  researchCostEnergy TEXT,
  researchCostWeapons TEXT,
  researchCostPropulsion TEXT,
  researchCostConstruction TEXT,
  researchCostElectronics TEXT,
  researchCostBiotechnology TEXT,
  techsStartHigh NUMERIC,
  spec TEXT,
  CONSTRAINT fkUsersRaces FOREIGN KEY (userId) REFERENCES users (id) ON DELETE CASCADE
);