syntax = "proto3";

package craig_stars.v1;

import "craig_stars/v1/battle.proto";
import "craig_stars/v1/common.proto";
import "craig_stars/v1/minefield.proto";
import "craig_stars/v1/mineralpacket.proto";
import "craig_stars/v1/mysterytrader.proto";
import "craig_stars/v1/planet.proto";
import "craig_stars/v1/rules.proto";
import "craig_stars/v1/shipdesign.proto";

message PlayerMessage {
  PlayerMessageTarget target = 1;
  PlayerMessageType type = 2;
  string text = 3;
  int32 battle_num = 4;
  PlayerMessageSpec spec = 5;
}

enum PlayerMessageTargetType {
  PLAYER_MESSAGE_TARGET_TYPE_UNSPECIFIED = 0;
  PLAYER_MESSAGE_TARGET_TYPE_PLANET = 1;
  PLAYER_MESSAGE_TARGET_TYPE_FLEET = 2;
  PLAYER_MESSAGE_TARGET_TYPE_WORMHOLE = 3;
  PLAYER_MESSAGE_TARGET_TYPE_MINEFIELD = 4;
  PLAYER_MESSAGE_TARGET_TYPE_MYSTERY_TRADER = 5;
  PLAYER_MESSAGE_TARGET_TYPE_MINERAL_PACKET = 6;
  PLAYER_MESSAGE_TARGET_TYPE_BATTLE = 7;
}

enum PlayerMessageType {
  PLAYER_MESSAGE_TYPE_UNSPECIFIED = 0;
  PLAYER_MESSAGE_TYPE_INFO = 1;
  PLAYER_MESSAGE_TYPE_ERROR = 2;
  PLAYER_MESSAGE_TYPE_PLANET_HOMEWORLD = 3;
  PLAYER_MESSAGE_TYPE_PLAYER_DISCOVERY = 4;
  PLAYER_MESSAGE_TYPE_PLANET_DISCOVERY = 5;
  PLAYER_MESSAGE_TYPE_PLANET_PRODUCTION_QUEUE_EMPTY = 6;
  PLAYER_MESSAGE_TYPE_PLANET_PRODUCTION_QUEUE_COMPLETE = 7;
  PLAYER_MESSAGE_TYPE_PLANET_BUILT_MINERAL_ALCHEMY = 8;
  PLAYER_MESSAGE_TYPE_PLANET_BUILT_MINE = 9;
  PLAYER_MESSAGE_TYPE_PLANET_BUILT_FACTORY = 10;
  PLAYER_MESSAGE_TYPE_PLANET_BUILT_DEFENSE = 11;
  PLAYER_MESSAGE_TYPE_FLEET_BUILT = 12;
  PLAYER_MESSAGE_TYPE_PLANET_BUILT_STARBASE = 13;
  PLAYER_MESSAGE_TYPE_PLANET_BUILT_SCANNER = 14;
  PLAYER_MESSAGE_TYPE_PLANET_BUILT_MINERAL_PACKET = 15;
  PLAYER_MESSAGE_TYPE_PLANET_BUILT_TERRAFORM = 16;
  PLAYER_MESSAGE_TYPE_FLEET_ORDERS_COMPLETE = 17;
  PLAYER_MESSAGE_TYPE_FLEET_ENGINE_FAILURE = 18;
  PLAYER_MESSAGE_TYPE_FLEET_OUT_OF_FUEL = 19;
  PLAYER_MESSAGE_TYPE_FLEET_GENERATED_FUEL = 20;
  PLAYER_MESSAGE_TYPE_FLEET_SCRAPPED = 21;
  PLAYER_MESSAGE_TYPE_FLEET_MERGED = 22;
  PLAYER_MESSAGE_TYPE_FLEET_MERGE_INVALID_NOT_FLEET = 23;
  PLAYER_MESSAGE_TYPE_FLEET_MERGE_INVALID_UNOWNED = 24;
  PLAYER_MESSAGE_TYPE_FLEET_PATROL_TARGETED = 25;
  PLAYER_MESSAGE_TYPE_FLEET_ROUTE_INVALID_NOT_FRIENDLY_PLANET = 26;
  PLAYER_MESSAGE_TYPE_FLEET_ROUTE_INVALID_NOT_PLANET = 27;
  PLAYER_MESSAGE_TYPE_FLEET_ROUTE_INVALID_NO_ROUTE_TARGET = 28;
  PLAYER_MESSAGE_TYPE_FLEET_TRANSPORT_INVALID = 29;
  PLAYER_MESSAGE_TYPE_FLEET_ROUTE = 30;
  PLAYER_MESSAGE_TYPE_INVALID = 31;
  PLAYER_MESSAGE_TYPE_PLANET_COLONIZED = 32;
  PLAYER_MESSAGE_TYPE_PLAYER_GAIN_TECH_LEVEL = 33;
  PLAYER_MESSAGE_TYPE_PLANET_BOMBED = 34;
  PLAYER_MESSAGE_TYPE_UNUSED1 = 35;
  PLAYER_MESSAGE_TYPE_FLEET_BOMBED_PLANET = 36;
  PLAYER_MESSAGE_TYPE_UNUSED2 = 37;
  PLAYER_MESSAGE_TYPE_PLANET_INVADED = 38;
  PLAYER_MESSAGE_TYPE_FLEET_INVADED_PLANET = 39;
  PLAYER_MESSAGE_TYPE_BATTLE = 40;
  PLAYER_MESSAGE_TYPE_FLEET_TRANSFERRED_CARGO = 41;
  PLAYER_MESSAGE_TYPE_FLEET_MINEFIELD_SWEPT_MINES = 42;
  PLAYER_MESSAGE_TYPE_FLEET_LAID_MINES = 43;
  PLAYER_MESSAGE_TYPE_FLEET_MINEFIELD_HIT = 44;
  PLAYER_MESSAGE_TYPE_FLEET_DUMPED_CARGO = 45;
  PLAYER_MESSAGE_TYPE_FLEET_STARGATE_DAMAGED = 46;
  PLAYER_MESSAGE_TYPE_PLANET_PACKET_CAUGHT = 47;
  PLAYER_MESSAGE_TYPE_PLANET_PACKET_DAMAGE = 48;
  PLAYER_MESSAGE_TYPE_PLANET_PACKET_LANDED = 49;
  PLAYER_MESSAGE_TYPE_MINERAL_PACKET_DISCOVERED = 50;
  PLAYER_MESSAGE_TYPE_MINERAL_PACKET_TARGETTING_PLAYER_DISCOVERED = 51;
  PLAYER_MESSAGE_TYPE_PLAYER_VICTOR = 52;
  PLAYER_MESSAGE_TYPE_FLEET_REPRODUCE = 53;
  PLAYER_MESSAGE_TYPE_PLANET_RANDOM_MINERAL_DEPOSIT = 54;
  PLAYER_MESSAGE_TYPE_PLANET_PERMAFORM = 55;
  PLAYER_MESSAGE_TYPE_PLANET_INSTAFORM = 56;
  PLAYER_MESSAGE_TYPE_PLANET_PACKET_TERRAFORM = 57;
  PLAYER_MESSAGE_TYPE_PLANET_PACKET_PERMAFORM = 58;
  PLAYER_MESSAGE_TYPE_FLEET_REMOTE_MINED = 59;
  PLAYER_MESSAGE_TYPE_PLAYER_TECH_GAINED = 60;
  PLAYER_MESSAGE_TYPE_FLEET_TARGET_LOST = 61;
  PLAYER_MESSAGE_TYPE_FLEET_RADIATING_ENGINE_DIEOFF = 62;
  PLAYER_MESSAGE_TYPE_PLANET_DIED_OFF = 63;
  PLAYER_MESSAGE_TYPE_PLANET_EMPTIED = 64;
  PLAYER_MESSAGE_TYPE_PLANET_DISCOVERY_HABITABLE = 65;
  PLAYER_MESSAGE_TYPE_PLANET_DISCOVERY_TERRAFORMABLE = 66;
  PLAYER_MESSAGE_TYPE_PLANET_DISCOVERY_UNINHABITABLE = 67;
  PLAYER_MESSAGE_TYPE_PLANET_BUILT_INVALID_ITEM = 68;
  PLAYER_MESSAGE_TYPE_PLANET_BUILT_INVALID_MINERAL_PACKET_NO_MASS_DRIVER = 69;
  PLAYER_MESSAGE_TYPE_PLANET_BUILT_INVALID_MINERAL_PACKET_NO_TARGET = 70;
  PLAYER_MESSAGE_TYPE_PLANET_POPULATION_DECREASED = 71;
  PLAYER_MESSAGE_TYPE_PLANET_POPULATION_DECREASED_OVERCROWDING = 72;
  PLAYER_MESSAGE_TYPE_PLAYER_DEAD = 73;
  PLAYER_MESSAGE_TYPE_PLAYER_NO_PLANETS = 74;
  PLAYER_MESSAGE_TYPE_PLANET_COMET_STRIKE = 75;
  PLAYER_MESSAGE_TYPE_PLANET_COMET_STRIKE_MY_PLANET = 76;
  PLAYER_MESSAGE_TYPE_FLEET_EXCEEDED_SAFE_SPEED = 77;
  PLAYER_MESSAGE_TYPE_PLANET_BONUS_RESEARCH_ARTIFACT = 78;
  PLAYER_MESSAGE_TYPE_FLEET_TRANSFER_GIVEN = 79;
  PLAYER_MESSAGE_TYPE_FLEET_TRANSFER_INVALID_PLAYER = 80;
  PLAYER_MESSAGE_TYPE_FLEET_TRANSFER_INVALID_COLONISTS = 81;
  PLAYER_MESSAGE_TYPE_FLEET_TRANSFER_INVALID_GIVE_REFUSED = 82;
  PLAYER_MESSAGE_TYPE_FLEET_TRANSFER_RECEIVED = 83;
  PLAYER_MESSAGE_TYPE_FLEET_TRANSFER_INVALID_RECEIVE = 84;
  PLAYER_MESSAGE_TYPE_FLEET_TRANSFER_INVALID_RECEIVE_REFUSED = 85;
  PLAYER_MESSAGE_TYPE_PLAYER_TECH_LEVEL_GAINED_INVASION = 86;
  PLAYER_MESSAGE_TYPE_PLAYER_TECH_LEVEL_GAINED_SCRAP_FLEET = 87;
  PLAYER_MESSAGE_TYPE_PLAYER_TECH_LEVEL_GAINED_BATTLE = 88;
  PLAYER_MESSAGE_TYPE_FLEET_DIEOFF = 89;
  PLAYER_MESSAGE_TYPE_BATTLE_ALLY = 90;
  PLAYER_MESSAGE_TYPE_BATTLE_REPORTS = 91;
  PLAYER_MESSAGE_TYPE_MYSTERY_TRADER_DISCOVERED = 92;
  PLAYER_MESSAGE_TYPE_MYSTERY_TRADER_CHANGED_COURSE = 93;
  PLAYER_MESSAGE_TYPE_MYSTERY_TRADER_AGAIN = 94;
  PLAYER_MESSAGE_TYPE_MYSTERY_TRADER_MET_WITH_REWARD = 95;
  PLAYER_MESSAGE_TYPE_MYSTERY_TRADER_MET_WITHOUT_REWARD = 96;
  PLAYER_MESSAGE_TYPE_MYSTERY_TRADER_ALREADY_REWARDED = 97;
  PLAYER_MESSAGE_TYPE_PLANET_BUILT_GENESIS_DEVICE = 98;
  PLAYER_MESSAGE_TYPE_PLAYER_ACQUIRABLE_PART_GAINED_SCRAP_FLEET = 99;
  PLAYER_MESSAGE_TYPE_PLAYER_ACQUIRABLE_PART_GAINED_BATTLE = 100;
  PLAYER_MESSAGE_TYPE_FLEET_BY_HAND_TRANSFER_INCOMPLETE = 101;
}

enum CargoTransferStatus {
  CARGO_TRANSFER_STATUS_UNSPECIFIED = 0;
  CARGO_TRANSFER_STATUS_OWNED = 1;
  CARGO_TRANSFER_STATUS_CARGO = 2;
  CARGO_TRANSFER_STATUS_CARGO_CAPACITY = 3;
  CARGO_TRANSFER_STATUS_DEST_CARGO = 4;
  CARGO_TRANSFER_STATUS_DEST_CARGO_CAPACITY = 5;
  CARGO_TRANSFER_STATUS_DEST_STARBASE = 6;
  CARGO_TRANSFER_STATUS_DEST_UNOWNED = 7;
}

message PlayerMessageSpec {
  MapObjectTarget map_object_target = 1;
  int32 amount = 2;
  int32 amount2 = 3;
  BattleRecordStats battle = 4;
  BombingResult bombing = 5;
  Cargo cargo = 6;
  PlayerMessageSpecCargoTransfer cargo_transfer = 7;
  PlayerMessageSpecComet comet = 8;
  Cost cost = 9;
  int32 dest_player_num = 10;
  string field = 11;
  PlayerMessageSpecInvasion invasion = 12;
  MapObjectType lost_target_type = 13;
  MinefieldDamage minefield_damage = 14;
  Mineral mineral = 15;
  MineralPacketDamage mineral_packet_damage = 16;
  PlayerMessageSpecMysteryTrader mystery_trader = 17;
  string name = 18;
  string next_field = 19;
  int32 prev_amount = 20;
  QueueItemType queue_item_type = 21;
  MapObjectTarget route_target = 22;
  int32 source_player_num = 23;
  string tech_gained = 24;
  Hab terraform_amount = 25;
}

message PlayerMessageSpecComet {
  CometSize size = 1;
  Mineral minerals_added = 2;
  Mineral mineral_concentration_increased = 3;
  Hab hab_changed = 4;
  int32 colonists_killed = 5;
}

message PlayerMessageSpecMysteryTrader {
  MysteryTraderRewardType type = 1;
  TechLevel tech_levels = 2;
  string tech = 3;
  ShipDesign ship = 4;
  int32 ship_count = 5;
  int32 fleet_num = 6;
}

message PlayerMessageSpecInvasion {
  string fleet_name = 1;
  int32 attacker_player_num = 2;
  int32 defender_player_num = 3;
  int32 attackers_killed = 4;
  int32 defenders_killed = 5;
  bool successful = 6;
}

message PlayerMessageSpecCargoTransfer {
  ResourceType cargo_type = 1;
  int32 transfered = 2;
  int32 wanted = 3;
  CargoTransferStatus status = 4;
}

message PlayerMessageTarget {
  Vector target_position = 1;
  PlayerMessageTargetType target_type = 2;
  string target_name = 3;
  int32 target_num = 4;
  int32 target_player_num = 5;
}

message BombingResult {
  string bomber_name = 1;
  int32 num_bombers = 2;
  int32 colonists_killed = 3;
  int32 mines_destroyed = 4;
  int32 factories_destroyed = 5;
  int32 defenses_destroyed = 6;
  Hab unterraform_amount = 7;
  bool planet_emptied = 8;
}
