syntax = "proto3";

package craig_stars.v1;

import "craig_stars/v1/minefield.proto";

service MinefieldService {
  rpc GetMinefield(GetMinefieldRequest) returns (GetMinefieldResponse);
  rpc UpdateMinefieldOrders(UpdateMinefieldOrdersRequest) returns (UpdateMinefieldOrdersResponse);
}

message GetMinefieldRequest {
  int64 game_id = 1;
  int32 minefield_num = 3;
}

message GetMinefieldResponse {
  Minefield minefield = 1;
}

message UpdateMinefieldOrdersRequest {
  int64 game_id = 1;
  int32 minefield_num = 2;
  MinefieldOrders minefield_orders = 3;
}

message UpdateMinefieldOrdersResponse {
  Minefield minefield = 1;
}
