syntax = "proto3";

package craig_stars.v1;

import "craig_stars/v1/fleet.proto";
import "craig_stars/v1/planet.proto";
import "craig_stars/v1/shipdesign.proto";

service ShipDesignService {
  rpc GetShipDesign(GetShipDesignRequest) returns (GetShipDesignResponse);
  rpc GetShipDesigns(GetShipDesignsRequest) returns (GetShipDesignsResponse);
  rpc CreateShipDesign(CreateShipDesignRequest) returns (CreateShipDesignResponse);
  rpc UpdateShipDesign(UpdateShipDesignRequest) returns (UpdateShipDesignResponse);
  rpc DeleteShipDesign(DeleteShipDesignRequest) returns (DeleteShipDesignResponse);
}

message GetShipDesignRequest {
  int64 game_id = 1;
  int32 num = 2;
}
message GetShipDesignResponse {
  ShipDesign design = 1;
}
message GetShipDesignsRequest {
  int64 game_id = 1;
}
message GetShipDesignsResponse {
  repeated ShipDesign design = 1;
}

message CreateShipDesignRequest {
  int64 game_id = 1;
  ShipDesign design = 2;
}
message CreateShipDesignResponse {
  ShipDesign design = 1;
}
message UpdateShipDesignRequest {
  int64 game_id = 1;
  ShipDesign design = 2;
}
message UpdateShipDesignResponse {
  ShipDesign design = 1;
}
message DeleteShipDesignRequest {
  int64 game_id = 1;
  int32 num = 2;
}
message DeleteShipDesignResponse {
  repeated Fleet fleets = 1;
  repeated Fleet starbases = 2;
  repeated Planet planets = 3;
}
