// @generated by protoc-gen-es v2.6.2 with parameter "target=ts,json_types=true"
// @generated from file craig_stars/v1/minefield.proto (package craig_stars.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { GameDBObject, GameDBObjectJson, MapObject, MapObjectJson } from "./common_pb";
import { file_craig_stars_v1_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file craig_stars/v1/minefield.proto.
 */
export const file_craig_stars_v1_minefield: GenFile = /*@__PURE__*/
  fileDesc("Ch5jcmFpZ19zdGFycy92MS9taW5lZmllbGQucHJvdG8SDmNyYWlnX3N0YXJzLnYxIvUBCglNaW5lZmllbGQSNAoOZ2FtZV9kYl9vYmplY3QYASABKAsyHC5jcmFpZ19zdGFycy52MS5HYW1lREJPYmplY3QSLQoKbWFwX29iamVjdBgCIAEoCzIZLmNyYWlnX3N0YXJzLnYxLk1hcE9iamVjdBI5ChBtaW5lZmllbGRfb3JkZXJzGAMgASgLMh8uY3JhaWdfc3RhcnMudjEuTWluZWZpZWxkT3JkZXJzEjUKDm1pbmVmaWVsZF90eXBlGAQgASgOMh0uY3JhaWdfc3RhcnMudjEuTWluZWZpZWxkVHlwZRIRCgludW1fbWluZXMYBSABKAUiIwoPTWluZWZpZWxkT3JkZXJzEhAKCGRldG9uYXRlGAEgASgIIkkKDU1pbmVmaWVsZFNwZWMSDgoGcmFkaXVzGAEgASgBEhIKCmRlY2F5X3JhdGUYAiABKAUSFAoMY2FuX2RldG9uYXRlGAMgASgIIvEBCg5NaW5lZmllbGRTdGF0cxIfChdtaW5fZGFtYWdlX3Blcl9mbGVldF9ycxgBIAEoBRIcChRkYW1hZ2VfcGVyX2VuZ2luZV9ycxgCIAEoBRIRCgltYXhfc3BlZWQYAyABKAUSFQoNY2hhbmNlX29mX2hpdBgEIAEoARIcChRtaW5fZGFtYWdlX3Blcl9mbGVldBgFIAEoBRIZChFkYW1hZ2VfcGVyX2VuZ2luZRgGIAEoBRIUCgxzd2VlcF9mYWN0b3IYByABKAESEQoJbWluX2RlY2F5GAggASgFEhQKDGNhbl9kZXRvbmF0ZRgJIAEoCCJTCg9NaW5lZmllbGREYW1hZ2USDgoGZGFtYWdlGAEgASgFEhcKD3NoaXBzX2Rlc3Ryb3llZBgCIAEoBRIXCg9mbGVldF9kZXN0cm95ZWQYAyABKAgqhQEKDU1pbmVmaWVsZFR5cGUSHgoaTUlORUZJRUxEX1RZUEVfVU5TUEVDSUZJRUQQABIbChdNSU5FRklFTERfVFlQRV9TVEFOREFSRBABEhgKFE1JTkVGSUVMRF9UWVBFX0hFQVZZEAISHQoZTUlORUZJRUxEX1RZUEVfU1BFRURfQlVNUBADYgZwcm90bzM", [file_craig_stars_v1_common]);

/**
 * @generated from message craig_stars.v1.Minefield
 */
export type Minefield = Message<"craig_stars.v1.Minefield"> & {
  /**
   * @generated from field: craig_stars.v1.GameDBObject game_db_object = 1;
   */
  gameDbObject?: GameDBObject;

  /**
   * @generated from field: craig_stars.v1.MapObject map_object = 2;
   */
  mapObject?: MapObject;

  /**
   * @generated from field: craig_stars.v1.MinefieldOrders minefield_orders = 3;
   */
  minefieldOrders?: MinefieldOrders;

  /**
   * @generated from field: craig_stars.v1.MinefieldType minefield_type = 4;
   */
  minefieldType: MinefieldType;

  /**
   * @generated from field: int32 num_mines = 5;
   */
  numMines: number;
};

/**
 * @generated from message craig_stars.v1.Minefield
 */
export type MinefieldJson = {
  /**
   * @generated from field: craig_stars.v1.GameDBObject game_db_object = 1;
   */
  gameDbObject?: GameDBObjectJson;

  /**
   * @generated from field: craig_stars.v1.MapObject map_object = 2;
   */
  mapObject?: MapObjectJson;

  /**
   * @generated from field: craig_stars.v1.MinefieldOrders minefield_orders = 3;
   */
  minefieldOrders?: MinefieldOrdersJson;

  /**
   * @generated from field: craig_stars.v1.MinefieldType minefield_type = 4;
   */
  minefieldType?: MinefieldTypeJson;

  /**
   * @generated from field: int32 num_mines = 5;
   */
  numMines?: number;
};

/**
 * Describes the message craig_stars.v1.Minefield.
 * Use `create(MinefieldSchema)` to create a new message.
 */
export const MinefieldSchema: GenMessage<Minefield, {jsonType: MinefieldJson}> = /*@__PURE__*/
  messageDesc(file_craig_stars_v1_minefield, 0);

/**
 * @generated from message craig_stars.v1.MinefieldOrders
 */
export type MinefieldOrders = Message<"craig_stars.v1.MinefieldOrders"> & {
  /**
   * @generated from field: bool detonate = 1;
   */
  detonate: boolean;
};

/**
 * @generated from message craig_stars.v1.MinefieldOrders
 */
export type MinefieldOrdersJson = {
  /**
   * @generated from field: bool detonate = 1;
   */
  detonate?: boolean;
};

/**
 * Describes the message craig_stars.v1.MinefieldOrders.
 * Use `create(MinefieldOrdersSchema)` to create a new message.
 */
export const MinefieldOrdersSchema: GenMessage<MinefieldOrders, {jsonType: MinefieldOrdersJson}> = /*@__PURE__*/
  messageDesc(file_craig_stars_v1_minefield, 1);

/**
 * @generated from message craig_stars.v1.MinefieldSpec
 */
export type MinefieldSpec = Message<"craig_stars.v1.MinefieldSpec"> & {
  /**
   * @generated from field: double radius = 1;
   */
  radius: number;

  /**
   * @generated from field: int32 decay_rate = 2;
   */
  decayRate: number;

  /**
   * @generated from field: bool can_detonate = 3;
   */
  canDetonate: boolean;
};

/**
 * @generated from message craig_stars.v1.MinefieldSpec
 */
export type MinefieldSpecJson = {
  /**
   * @generated from field: double radius = 1;
   */
  radius?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: int32 decay_rate = 2;
   */
  decayRate?: number;

  /**
   * @generated from field: bool can_detonate = 3;
   */
  canDetonate?: boolean;
};

/**
 * Describes the message craig_stars.v1.MinefieldSpec.
 * Use `create(MinefieldSpecSchema)` to create a new message.
 */
export const MinefieldSpecSchema: GenMessage<MinefieldSpec, {jsonType: MinefieldSpecJson}> = /*@__PURE__*/
  messageDesc(file_craig_stars_v1_minefield, 2);

/**
 * @generated from message craig_stars.v1.MinefieldStats
 */
export type MinefieldStats = Message<"craig_stars.v1.MinefieldStats"> & {
  /**
   * @generated from field: int32 min_damage_per_fleet_rs = 1;
   */
  minDamagePerFleetRs: number;

  /**
   * @generated from field: int32 damage_per_engine_rs = 2;
   */
  damagePerEngineRs: number;

  /**
   * @generated from field: int32 max_speed = 3;
   */
  maxSpeed: number;

  /**
   * @generated from field: double chance_of_hit = 4;
   */
  chanceOfHit: number;

  /**
   * @generated from field: int32 min_damage_per_fleet = 5;
   */
  minDamagePerFleet: number;

  /**
   * @generated from field: int32 damage_per_engine = 6;
   */
  damagePerEngine: number;

  /**
   * @generated from field: double sweep_factor = 7;
   */
  sweepFactor: number;

  /**
   * @generated from field: int32 min_decay = 8;
   */
  minDecay: number;

  /**
   * @generated from field: bool can_detonate = 9;
   */
  canDetonate: boolean;
};

/**
 * @generated from message craig_stars.v1.MinefieldStats
 */
export type MinefieldStatsJson = {
  /**
   * @generated from field: int32 min_damage_per_fleet_rs = 1;
   */
  minDamagePerFleetRs?: number;

  /**
   * @generated from field: int32 damage_per_engine_rs = 2;
   */
  damagePerEngineRs?: number;

  /**
   * @generated from field: int32 max_speed = 3;
   */
  maxSpeed?: number;

  /**
   * @generated from field: double chance_of_hit = 4;
   */
  chanceOfHit?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: int32 min_damage_per_fleet = 5;
   */
  minDamagePerFleet?: number;

  /**
   * @generated from field: int32 damage_per_engine = 6;
   */
  damagePerEngine?: number;

  /**
   * @generated from field: double sweep_factor = 7;
   */
  sweepFactor?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: int32 min_decay = 8;
   */
  minDecay?: number;

  /**
   * @generated from field: bool can_detonate = 9;
   */
  canDetonate?: boolean;
};

/**
 * Describes the message craig_stars.v1.MinefieldStats.
 * Use `create(MinefieldStatsSchema)` to create a new message.
 */
export const MinefieldStatsSchema: GenMessage<MinefieldStats, {jsonType: MinefieldStatsJson}> = /*@__PURE__*/
  messageDesc(file_craig_stars_v1_minefield, 3);

/**
 * @generated from message craig_stars.v1.MinefieldDamage
 */
export type MinefieldDamage = Message<"craig_stars.v1.MinefieldDamage"> & {
  /**
   * @generated from field: int32 damage = 1;
   */
  damage: number;

  /**
   * @generated from field: int32 ships_destroyed = 2;
   */
  shipsDestroyed: number;

  /**
   * @generated from field: bool fleet_destroyed = 3;
   */
  fleetDestroyed: boolean;
};

/**
 * @generated from message craig_stars.v1.MinefieldDamage
 */
export type MinefieldDamageJson = {
  /**
   * @generated from field: int32 damage = 1;
   */
  damage?: number;

  /**
   * @generated from field: int32 ships_destroyed = 2;
   */
  shipsDestroyed?: number;

  /**
   * @generated from field: bool fleet_destroyed = 3;
   */
  fleetDestroyed?: boolean;
};

/**
 * Describes the message craig_stars.v1.MinefieldDamage.
 * Use `create(MinefieldDamageSchema)` to create a new message.
 */
export const MinefieldDamageSchema: GenMessage<MinefieldDamage, {jsonType: MinefieldDamageJson}> = /*@__PURE__*/
  messageDesc(file_craig_stars_v1_minefield, 4);

/**
 * @generated from enum craig_stars.v1.MinefieldType
 */
export enum MinefieldType {
  /**
   * @generated from enum value: MINEFIELD_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: MINEFIELD_TYPE_STANDARD = 1;
   */
  STANDARD = 1,

  /**
   * @generated from enum value: MINEFIELD_TYPE_HEAVY = 2;
   */
  HEAVY = 2,

  /**
   * @generated from enum value: MINEFIELD_TYPE_SPEED_BUMP = 3;
   */
  SPEED_BUMP = 3,
}

/**
 * @generated from enum craig_stars.v1.MinefieldType
 */
export type MinefieldTypeJson = "MINEFIELD_TYPE_UNSPECIFIED" | "MINEFIELD_TYPE_STANDARD" | "MINEFIELD_TYPE_HEAVY" | "MINEFIELD_TYPE_SPEED_BUMP";

/**
 * Describes the enum craig_stars.v1.MinefieldType.
 */
export const MinefieldTypeSchema: GenEnum<MinefieldType, MinefieldTypeJson> = /*@__PURE__*/
  enumDesc(file_craig_stars_v1_minefield, 0);

