// @generated by protoc-gen-es v2.6.2 with parameter "target=ts,json_types=true"
// @generated from file craig_stars/v1/raceservice.proto (package craig_stars.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Race, RaceJson } from "./race_pb";
import { file_craig_stars_v1_race } from "./race_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file craig_stars/v1/raceservice.proto.
 */
export const file_craig_stars_v1_raceservice: GenFile = /*@__PURE__*/
  fileDesc("CiBjcmFpZ19zdGFycy92MS9yYWNlc2VydmljZS5wcm90bxIOY3JhaWdfc3RhcnMudjEiEQoPR2V0UmFjZXNSZXF1ZXN0IjcKEEdldFJhY2VzUmVzcG9uc2USIwoFcmFjZXMYASADKAsyFC5jcmFpZ19zdGFycy52MS5SYWNlIiEKDkdldFJhY2VSZXF1ZXN0Eg8KB3JhY2VfaWQYASABKAMiNQoPR2V0UmFjZVJlc3BvbnNlEiIKBHJhY2UYASABKAsyFC5jcmFpZ19zdGFycy52MS5SYWNlIjcKEUNyZWF0ZVJhY2VSZXF1ZXN0EiIKBHJhY2UYASABKAsyFC5jcmFpZ19zdGFycy52MS5SYWNlIjgKEkNyZWF0ZVJhY2VSZXNwb25zZRIiCgRyYWNlGAEgASgLMhQuY3JhaWdfc3RhcnMudjEuUmFjZSI3ChFVcGRhdGVSYWNlUmVxdWVzdBIiCgRyYWNlGAEgASgLMhQuY3JhaWdfc3RhcnMudjEuUmFjZSI4ChJVcGRhdGVSYWNlUmVzcG9uc2USIgoEcmFjZRgBIAEoCzIULmNyYWlnX3N0YXJzLnYxLlJhY2UiJAoRRGVsZXRlUmFjZVJlcXVlc3QSDwoHcmFjZV9pZBgBIAEoAyIUChJEZWxldGVSYWNlUmVzcG9uc2UypwMKC1JhY2VTZXJ2aWNlEk0KCEdldFJhY2VzEh8uY3JhaWdfc3RhcnMudjEuR2V0UmFjZXNSZXF1ZXN0GiAuY3JhaWdfc3RhcnMudjEuR2V0UmFjZXNSZXNwb25zZRJKCgdHZXRSYWNlEh4uY3JhaWdfc3RhcnMudjEuR2V0UmFjZVJlcXVlc3QaHy5jcmFpZ19zdGFycy52MS5HZXRSYWNlUmVzcG9uc2USUwoKQ3JlYXRlUmFjZRIhLmNyYWlnX3N0YXJzLnYxLkNyZWF0ZVJhY2VSZXF1ZXN0GiIuY3JhaWdfc3RhcnMudjEuQ3JlYXRlUmFjZVJlc3BvbnNlElMKClVwZGF0ZVJhY2USIS5jcmFpZ19zdGFycy52MS5VcGRhdGVSYWNlUmVxdWVzdBoiLmNyYWlnX3N0YXJzLnYxLlVwZGF0ZVJhY2VSZXNwb25zZRJTCgpEZWxldGVSYWNlEiEuY3JhaWdfc3RhcnMudjEuRGVsZXRlUmFjZVJlcXVlc3QaIi5jcmFpZ19zdGFycy52MS5EZWxldGVSYWNlUmVzcG9uc2ViBnByb3RvMw", [file_craig_stars_v1_race]);

/**
 * @generated from message craig_stars.v1.GetRacesRequest
 */
export type GetRacesRequest = Message<"craig_stars.v1.GetRacesRequest"> & {
};

/**
 * @generated from message craig_stars.v1.GetRacesRequest
 */
export type GetRacesRequestJson = {
};

/**
 * Describes the message craig_stars.v1.GetRacesRequest.
 * Use `create(GetRacesRequestSchema)` to create a new message.
 */
export const GetRacesRequestSchema: GenMessage<GetRacesRequest, {jsonType: GetRacesRequestJson}> = /*@__PURE__*/
  messageDesc(file_craig_stars_v1_raceservice, 0);

/**
 * @generated from message craig_stars.v1.GetRacesResponse
 */
export type GetRacesResponse = Message<"craig_stars.v1.GetRacesResponse"> & {
  /**
   * @generated from field: repeated craig_stars.v1.Race races = 1;
   */
  races: Race[];
};

/**
 * @generated from message craig_stars.v1.GetRacesResponse
 */
export type GetRacesResponseJson = {
  /**
   * @generated from field: repeated craig_stars.v1.Race races = 1;
   */
  races?: RaceJson[];
};

/**
 * Describes the message craig_stars.v1.GetRacesResponse.
 * Use `create(GetRacesResponseSchema)` to create a new message.
 */
export const GetRacesResponseSchema: GenMessage<GetRacesResponse, {jsonType: GetRacesResponseJson}> = /*@__PURE__*/
  messageDesc(file_craig_stars_v1_raceservice, 1);

/**
 * @generated from message craig_stars.v1.GetRaceRequest
 */
export type GetRaceRequest = Message<"craig_stars.v1.GetRaceRequest"> & {
  /**
   * @generated from field: int64 race_id = 1;
   */
  raceId: bigint;
};

/**
 * @generated from message craig_stars.v1.GetRaceRequest
 */
export type GetRaceRequestJson = {
  /**
   * @generated from field: int64 race_id = 1;
   */
  raceId?: string;
};

/**
 * Describes the message craig_stars.v1.GetRaceRequest.
 * Use `create(GetRaceRequestSchema)` to create a new message.
 */
export const GetRaceRequestSchema: GenMessage<GetRaceRequest, {jsonType: GetRaceRequestJson}> = /*@__PURE__*/
  messageDesc(file_craig_stars_v1_raceservice, 2);

/**
 * @generated from message craig_stars.v1.GetRaceResponse
 */
export type GetRaceResponse = Message<"craig_stars.v1.GetRaceResponse"> & {
  /**
   * @generated from field: craig_stars.v1.Race race = 1;
   */
  race?: Race;
};

/**
 * @generated from message craig_stars.v1.GetRaceResponse
 */
export type GetRaceResponseJson = {
  /**
   * @generated from field: craig_stars.v1.Race race = 1;
   */
  race?: RaceJson;
};

/**
 * Describes the message craig_stars.v1.GetRaceResponse.
 * Use `create(GetRaceResponseSchema)` to create a new message.
 */
export const GetRaceResponseSchema: GenMessage<GetRaceResponse, {jsonType: GetRaceResponseJson}> = /*@__PURE__*/
  messageDesc(file_craig_stars_v1_raceservice, 3);

/**
 * @generated from message craig_stars.v1.CreateRaceRequest
 */
export type CreateRaceRequest = Message<"craig_stars.v1.CreateRaceRequest"> & {
  /**
   * @generated from field: craig_stars.v1.Race race = 1;
   */
  race?: Race;
};

/**
 * @generated from message craig_stars.v1.CreateRaceRequest
 */
export type CreateRaceRequestJson = {
  /**
   * @generated from field: craig_stars.v1.Race race = 1;
   */
  race?: RaceJson;
};

/**
 * Describes the message craig_stars.v1.CreateRaceRequest.
 * Use `create(CreateRaceRequestSchema)` to create a new message.
 */
export const CreateRaceRequestSchema: GenMessage<CreateRaceRequest, {jsonType: CreateRaceRequestJson}> = /*@__PURE__*/
  messageDesc(file_craig_stars_v1_raceservice, 4);

/**
 * @generated from message craig_stars.v1.CreateRaceResponse
 */
export type CreateRaceResponse = Message<"craig_stars.v1.CreateRaceResponse"> & {
  /**
   * @generated from field: craig_stars.v1.Race race = 1;
   */
  race?: Race;
};

/**
 * @generated from message craig_stars.v1.CreateRaceResponse
 */
export type CreateRaceResponseJson = {
  /**
   * @generated from field: craig_stars.v1.Race race = 1;
   */
  race?: RaceJson;
};

/**
 * Describes the message craig_stars.v1.CreateRaceResponse.
 * Use `create(CreateRaceResponseSchema)` to create a new message.
 */
export const CreateRaceResponseSchema: GenMessage<CreateRaceResponse, {jsonType: CreateRaceResponseJson}> = /*@__PURE__*/
  messageDesc(file_craig_stars_v1_raceservice, 5);

/**
 * @generated from message craig_stars.v1.UpdateRaceRequest
 */
export type UpdateRaceRequest = Message<"craig_stars.v1.UpdateRaceRequest"> & {
  /**
   * @generated from field: craig_stars.v1.Race race = 1;
   */
  race?: Race;
};

/**
 * @generated from message craig_stars.v1.UpdateRaceRequest
 */
export type UpdateRaceRequestJson = {
  /**
   * @generated from field: craig_stars.v1.Race race = 1;
   */
  race?: RaceJson;
};

/**
 * Describes the message craig_stars.v1.UpdateRaceRequest.
 * Use `create(UpdateRaceRequestSchema)` to create a new message.
 */
export const UpdateRaceRequestSchema: GenMessage<UpdateRaceRequest, {jsonType: UpdateRaceRequestJson}> = /*@__PURE__*/
  messageDesc(file_craig_stars_v1_raceservice, 6);

/**
 * @generated from message craig_stars.v1.UpdateRaceResponse
 */
export type UpdateRaceResponse = Message<"craig_stars.v1.UpdateRaceResponse"> & {
  /**
   * @generated from field: craig_stars.v1.Race race = 1;
   */
  race?: Race;
};

/**
 * @generated from message craig_stars.v1.UpdateRaceResponse
 */
export type UpdateRaceResponseJson = {
  /**
   * @generated from field: craig_stars.v1.Race race = 1;
   */
  race?: RaceJson;
};

/**
 * Describes the message craig_stars.v1.UpdateRaceResponse.
 * Use `create(UpdateRaceResponseSchema)` to create a new message.
 */
export const UpdateRaceResponseSchema: GenMessage<UpdateRaceResponse, {jsonType: UpdateRaceResponseJson}> = /*@__PURE__*/
  messageDesc(file_craig_stars_v1_raceservice, 7);

/**
 * @generated from message craig_stars.v1.DeleteRaceRequest
 */
export type DeleteRaceRequest = Message<"craig_stars.v1.DeleteRaceRequest"> & {
  /**
   * @generated from field: int64 race_id = 1;
   */
  raceId: bigint;
};

/**
 * @generated from message craig_stars.v1.DeleteRaceRequest
 */
export type DeleteRaceRequestJson = {
  /**
   * @generated from field: int64 race_id = 1;
   */
  raceId?: string;
};

/**
 * Describes the message craig_stars.v1.DeleteRaceRequest.
 * Use `create(DeleteRaceRequestSchema)` to create a new message.
 */
export const DeleteRaceRequestSchema: GenMessage<DeleteRaceRequest, {jsonType: DeleteRaceRequestJson}> = /*@__PURE__*/
  messageDesc(file_craig_stars_v1_raceservice, 8);

/**
 * @generated from message craig_stars.v1.DeleteRaceResponse
 */
export type DeleteRaceResponse = Message<"craig_stars.v1.DeleteRaceResponse"> & {
};

/**
 * @generated from message craig_stars.v1.DeleteRaceResponse
 */
export type DeleteRaceResponseJson = {
};

/**
 * Describes the message craig_stars.v1.DeleteRaceResponse.
 * Use `create(DeleteRaceResponseSchema)` to create a new message.
 */
export const DeleteRaceResponseSchema: GenMessage<DeleteRaceResponse, {jsonType: DeleteRaceResponseJson}> = /*@__PURE__*/
  messageDesc(file_craig_stars_v1_raceservice, 9);

/**
 * @generated from service craig_stars.v1.RaceService
 */
export const RaceService: GenService<{
  /**
   * @generated from rpc craig_stars.v1.RaceService.GetRaces
   */
  getRaces: {
    methodKind: "unary";
    input: typeof GetRacesRequestSchema;
    output: typeof GetRacesResponseSchema;
  },
  /**
   * @generated from rpc craig_stars.v1.RaceService.GetRace
   */
  getRace: {
    methodKind: "unary";
    input: typeof GetRaceRequestSchema;
    output: typeof GetRaceResponseSchema;
  },
  /**
   * @generated from rpc craig_stars.v1.RaceService.CreateRace
   */
  createRace: {
    methodKind: "unary";
    input: typeof CreateRaceRequestSchema;
    output: typeof CreateRaceResponseSchema;
  },
  /**
   * @generated from rpc craig_stars.v1.RaceService.UpdateRace
   */
  updateRace: {
    methodKind: "unary";
    input: typeof UpdateRaceRequestSchema;
    output: typeof UpdateRaceResponseSchema;
  },
  /**
   * @generated from rpc craig_stars.v1.RaceService.DeleteRace
   */
  deleteRace: {
    methodKind: "unary";
    input: typeof DeleteRaceRequestSchema;
    output: typeof DeleteRaceResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_craig_stars_v1_raceservice, 0);

