// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,json_types=true"
// @generated from file craig_stars/v1/salvage.proto (package craig_stars.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Cargo, CargoJson, GameDBObject, GameDBObjectJson, MapObject, MapObjectJson } from "./common_pb";
import { file_craig_stars_v1_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file craig_stars/v1/salvage.proto.
 */
export const file_craig_stars_v1_salvage: GenFile = /*@__PURE__*/
  fileDesc("ChxjcmFpZ19zdGFycy92MS9zYWx2YWdlLnByb3RvEg5jcmFpZ19zdGFycy52MSKUAQoHU2FsdmFnZRI0Cg5nYW1lX2RiX29iamVjdBgBIAEoCzIcLmNyYWlnX3N0YXJzLnYxLkdhbWVEQk9iamVjdBItCgptYXBfb2JqZWN0GAIgASgLMhkuY3JhaWdfc3RhcnMudjEuTWFwT2JqZWN0EiQKBWNhcmdvGAMgASgLMhUuY3JhaWdfc3RhcnMudjEuQ2FyZ29iBnByb3RvMw", [file_craig_stars_v1_common]);

/**
 * @generated from message craig_stars.v1.Salvage
 */
export type Salvage = Message<"craig_stars.v1.Salvage"> & {
  /**
   * @generated from field: craig_stars.v1.GameDBObject game_db_object = 1;
   */
  gameDbObject?: GameDBObject | undefined;

  /**
   * @generated from field: craig_stars.v1.MapObject map_object = 2;
   */
  mapObject?: MapObject | undefined;

  /**
   * @generated from field: craig_stars.v1.Cargo cargo = 3;
   */
  cargo?: Cargo | undefined;
};

/**
 * @generated from message craig_stars.v1.Salvage
 */
export type SalvageJson = {
  /**
   * @generated from field: craig_stars.v1.GameDBObject game_db_object = 1;
   */
  gameDbObject?: GameDBObjectJson;

  /**
   * @generated from field: craig_stars.v1.MapObject map_object = 2;
   */
  mapObject?: MapObjectJson;

  /**
   * @generated from field: craig_stars.v1.Cargo cargo = 3;
   */
  cargo?: CargoJson;
};

/**
 * Describes the message craig_stars.v1.Salvage.
 * Use `create(SalvageSchema)` to create a new message.
 */
export const SalvageSchema: GenMessage<Salvage, {jsonType: SalvageJson}> = /*@__PURE__*/
  messageDesc(file_craig_stars_v1_salvage, 0);

