// @generated by protoc-gen-es v2.6.2 with parameter "target=ts,json_types=true"
// @generated from file craig_stars/v1/score.proto (package craig_stars.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file craig_stars/v1/score.proto.
 */
export const file_craig_stars_v1_score: GenFile = /*@__PURE__*/
  fileDesc("ChpjcmFpZ19zdGFycy92MS9zY29yZS5wcm90bxIOY3JhaWdfc3RhcnMudjEi3wEKC1BsYXllclNjb3JlEg8KB3BsYW5ldHMYASABKAUSEQoJc3RhcmJhc2VzGAIgASgFEhUKDXVuYXJtZWRfc2hpcHMYAyABKAUSFAoMZXNjb3J0X3NoaXBzGAQgASgFEhUKDWNhcGl0YWxfc2hpcHMYBSABKAUSEwoLdGVjaF9sZXZlbHMYBiABKAUSEQoJcmVzb3VyY2VzGAcgASgFEg0KBXNjb3JlGAggASgFEgwKBHJhbmsYCSABKAUSIwobYWNoaWV2ZWRfdmljdG9yeV9jb25kaXRpb25zGAogASgNYgZwcm90bzM");

/**
 * @generated from message craig_stars.v1.PlayerScore
 */
export type PlayerScore = Message<"craig_stars.v1.PlayerScore"> & {
  /**
   * @generated from field: int32 planets = 1;
   */
  planets: number;

  /**
   * @generated from field: int32 starbases = 2;
   */
  starbases: number;

  /**
   * @generated from field: int32 unarmed_ships = 3;
   */
  unarmedShips: number;

  /**
   * @generated from field: int32 escort_ships = 4;
   */
  escortShips: number;

  /**
   * @generated from field: int32 capital_ships = 5;
   */
  capitalShips: number;

  /**
   * @generated from field: int32 tech_levels = 6;
   */
  techLevels: number;

  /**
   * @generated from field: int32 resources = 7;
   */
  resources: number;

  /**
   * @generated from field: int32 score = 8;
   */
  score: number;

  /**
   * @generated from field: int32 rank = 9;
   */
  rank: number;

  /**
   * @generated from field: uint32 achieved_victory_conditions = 10;
   */
  achievedVictoryConditions: number;
};

/**
 * @generated from message craig_stars.v1.PlayerScore
 */
export type PlayerScoreJson = {
  /**
   * @generated from field: int32 planets = 1;
   */
  planets?: number;

  /**
   * @generated from field: int32 starbases = 2;
   */
  starbases?: number;

  /**
   * @generated from field: int32 unarmed_ships = 3;
   */
  unarmedShips?: number;

  /**
   * @generated from field: int32 escort_ships = 4;
   */
  escortShips?: number;

  /**
   * @generated from field: int32 capital_ships = 5;
   */
  capitalShips?: number;

  /**
   * @generated from field: int32 tech_levels = 6;
   */
  techLevels?: number;

  /**
   * @generated from field: int32 resources = 7;
   */
  resources?: number;

  /**
   * @generated from field: int32 score = 8;
   */
  score?: number;

  /**
   * @generated from field: int32 rank = 9;
   */
  rank?: number;

  /**
   * @generated from field: uint32 achieved_victory_conditions = 10;
   */
  achievedVictoryConditions?: number;
};

/**
 * Describes the message craig_stars.v1.PlayerScore.
 * Use `create(PlayerScoreSchema)` to create a new message.
 */
export const PlayerScoreSchema: GenMessage<PlayerScore, {jsonType: PlayerScoreJson}> = /*@__PURE__*/
  messageDesc(file_craig_stars_v1_score, 0);

