// @generated by protoc-gen-es v2.6.2 with parameter "target=ts,json_types=true"
// @generated from file craig_stars/v1/testservice.proto (package craig_stars.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { GameWithPlayers, GameWithPlayersJson } from "./game_pb";
import { file_craig_stars_v1_game } from "./game_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file craig_stars/v1/testservice.proto.
 */
export const file_craig_stars_v1_testservice: GenFile = /*@__PURE__*/
  fileDesc("CiBjcmFpZ19zdGFycy92MS90ZXN0c2VydmljZS5wcm90bxIOY3JhaWdfc3RhcnMudjEiQgoVQ3JlYXRlVGVzdEdhbWVSZXF1ZXN0EhYKDnRlc3RfZ2FtZV9uYW1lGAEgASgJEhEKCWdhbWVfbmFtZRgCIAEoCSJHChZDcmVhdGVUZXN0R2FtZVJlc3BvbnNlEi0KBGdhbWUYASABKAsyHy5jcmFpZ19zdGFycy52MS5HYW1lV2l0aFBsYXllcnMiGQoXR2V0VGVzdEdhbWVOYW1lc1JlcXVlc3QiKQoYR2V0VGVzdEdhbWVOYW1lc1Jlc3BvbnNlEg0KBW5hbWVzGAEgAygJMtUBCgtUZXN0U2VydmljZRJfCg5DcmVhdGVUZXN0R2FtZRIlLmNyYWlnX3N0YXJzLnYxLkNyZWF0ZVRlc3RHYW1lUmVxdWVzdBomLmNyYWlnX3N0YXJzLnYxLkNyZWF0ZVRlc3RHYW1lUmVzcG9uc2USZQoQR2V0VGVzdEdhbWVOYW1lcxInLmNyYWlnX3N0YXJzLnYxLkdldFRlc3RHYW1lTmFtZXNSZXF1ZXN0GiguY3JhaWdfc3RhcnMudjEuR2V0VGVzdEdhbWVOYW1lc1Jlc3BvbnNlYgZwcm90bzM", [file_craig_stars_v1_game]);

/**
 * @generated from message craig_stars.v1.CreateTestGameRequest
 */
export type CreateTestGameRequest = Message<"craig_stars.v1.CreateTestGameRequest"> & {
  /**
   * @generated from field: string test_game_name = 1;
   */
  testGameName: string;

  /**
   * @generated from field: string game_name = 2;
   */
  gameName: string;
};

/**
 * @generated from message craig_stars.v1.CreateTestGameRequest
 */
export type CreateTestGameRequestJson = {
  /**
   * @generated from field: string test_game_name = 1;
   */
  testGameName?: string;

  /**
   * @generated from field: string game_name = 2;
   */
  gameName?: string;
};

/**
 * Describes the message craig_stars.v1.CreateTestGameRequest.
 * Use `create(CreateTestGameRequestSchema)` to create a new message.
 */
export const CreateTestGameRequestSchema: GenMessage<CreateTestGameRequest, {jsonType: CreateTestGameRequestJson}> = /*@__PURE__*/
  messageDesc(file_craig_stars_v1_testservice, 0);

/**
 * @generated from message craig_stars.v1.CreateTestGameResponse
 */
export type CreateTestGameResponse = Message<"craig_stars.v1.CreateTestGameResponse"> & {
  /**
   * @generated from field: craig_stars.v1.GameWithPlayers game = 1;
   */
  game?: GameWithPlayers;
};

/**
 * @generated from message craig_stars.v1.CreateTestGameResponse
 */
export type CreateTestGameResponseJson = {
  /**
   * @generated from field: craig_stars.v1.GameWithPlayers game = 1;
   */
  game?: GameWithPlayersJson;
};

/**
 * Describes the message craig_stars.v1.CreateTestGameResponse.
 * Use `create(CreateTestGameResponseSchema)` to create a new message.
 */
export const CreateTestGameResponseSchema: GenMessage<CreateTestGameResponse, {jsonType: CreateTestGameResponseJson}> = /*@__PURE__*/
  messageDesc(file_craig_stars_v1_testservice, 1);

/**
 * @generated from message craig_stars.v1.GetTestGameNamesRequest
 */
export type GetTestGameNamesRequest = Message<"craig_stars.v1.GetTestGameNamesRequest"> & {
};

/**
 * @generated from message craig_stars.v1.GetTestGameNamesRequest
 */
export type GetTestGameNamesRequestJson = {
};

/**
 * Describes the message craig_stars.v1.GetTestGameNamesRequest.
 * Use `create(GetTestGameNamesRequestSchema)` to create a new message.
 */
export const GetTestGameNamesRequestSchema: GenMessage<GetTestGameNamesRequest, {jsonType: GetTestGameNamesRequestJson}> = /*@__PURE__*/
  messageDesc(file_craig_stars_v1_testservice, 2);

/**
 * @generated from message craig_stars.v1.GetTestGameNamesResponse
 */
export type GetTestGameNamesResponse = Message<"craig_stars.v1.GetTestGameNamesResponse"> & {
  /**
   * @generated from field: repeated string names = 1;
   */
  names: string[];
};

/**
 * @generated from message craig_stars.v1.GetTestGameNamesResponse
 */
export type GetTestGameNamesResponseJson = {
  /**
   * @generated from field: repeated string names = 1;
   */
  names?: string[];
};

/**
 * Describes the message craig_stars.v1.GetTestGameNamesResponse.
 * Use `create(GetTestGameNamesResponseSchema)` to create a new message.
 */
export const GetTestGameNamesResponseSchema: GenMessage<GetTestGameNamesResponse, {jsonType: GetTestGameNamesResponseJson}> = /*@__PURE__*/
  messageDesc(file_craig_stars_v1_testservice, 3);

/**
 * @generated from service craig_stars.v1.TestService
 */
export const TestService: GenService<{
  /**
   * @generated from rpc craig_stars.v1.TestService.CreateTestGame
   */
  createTestGame: {
    methodKind: "unary";
    input: typeof CreateTestGameRequestSchema;
    output: typeof CreateTestGameResponseSchema;
  },
  /**
   * @generated from rpc craig_stars.v1.TestService.GetTestGameNames
   */
  getTestGameNames: {
    methodKind: "unary";
    input: typeof GetTestGameNamesRequestSchema;
    output: typeof GetTestGameNamesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_craig_stars_v1_testservice, 0);

