// @generated by protoc-gen-es v2.6.2 with parameter "target=ts,json_types=true"
// @generated from file craig_stars/v1/wormhole.proto (package craig_stars.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { GameDBObject, GameDBObjectJson, MapObject, MapObjectJson } from "./common_pb";
import { file_craig_stars_v1_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file craig_stars/v1/wormhole.proto.
 */
export const file_craig_stars_v1_wormhole: GenFile = /*@__PURE__*/
  fileDesc("Ch1jcmFpZ19zdGFycy92MS93b3JtaG9sZS5wcm90bxIOY3JhaWdfc3RhcnMudjEihgIKCFdvcm1ob2xlEjQKDmdhbWVfZGJfb2JqZWN0GAEgASgLMhwuY3JhaWdfc3RhcnMudjEuR2FtZURCT2JqZWN0Ei0KCm1hcF9vYmplY3QYAiABKAsyGS5jcmFpZ19zdGFycy52MS5NYXBPYmplY3QSFwoPZGVzdGluYXRpb25fbnVtGAMgASgFEjQKCXN0YWJpbGl0eRgEIAEoDjIhLmNyYWlnX3N0YXJzLnYxLldvcm1ob2xlU3RhYmlsaXR5EhoKEnllYXJzX2F0X3N0YWJpbGl0eRgFIAEoBRIqCgRzcGVjGAYgASgLMhwuY3JhaWdfc3RhcnMudjEuV29ybWhvbGVTcGVjIjwKDFdvcm1ob2xlU3BlYxIsCgVzdGF0cxgBIAEoCzIdLmNyYWlnX3N0YXJzLnYxLldvcm1ob2xlU3RhdHMiWgoNV29ybWhvbGVTdGF0cxIYChB5ZWFyc190b19kZWdyYWRlGAEgASgFEhYKDmNoYW5jZV90b19qdW1wGAIgASgBEhcKD2ppZ2dsZV9kaXN0YW5jZRgDIAEoBSq1AgoRV29ybWhvbGVTdGFiaWxpdHkSIgoeV09STUhPTEVfU1RBQklMSVRZX1VOU1BFQ0lGSUVEEAASIQodV09STUhPTEVfU1RBQklMSVRZX1JPQ0tfU09MSUQQARIdChlXT1JNSE9MRV9TVEFCSUxJVFlfU1RBQkxFEAISJAogV09STUhPTEVfU1RBQklMSVRZX01PU1RMWV9TVEFCTEUQAxIeChpXT1JNSE9MRV9TVEFCSUxJVFlfQVZFUkFHRRAEEigKJFdPUk1IT0xFX1NUQUJJTElUWV9TTElHSFRMWV9WT0xBVElMRRAFEh8KG1dPUk1IT0xFX1NUQUJJTElUWV9WT0xBVElMRRAGEikKJVdPUk1IT0xFX1NUQUJJTElUWV9FWFRSRU1FTFlfVk9MQVRJTEUQB2IGcHJvdG8z", [file_craig_stars_v1_common]);

/**
 * @generated from message craig_stars.v1.Wormhole
 */
export type Wormhole = Message<"craig_stars.v1.Wormhole"> & {
  /**
   * @generated from field: craig_stars.v1.GameDBObject game_db_object = 1;
   */
  gameDbObject?: GameDBObject;

  /**
   * @generated from field: craig_stars.v1.MapObject map_object = 2;
   */
  mapObject?: MapObject;

  /**
   * @generated from field: int32 destination_num = 3;
   */
  destinationNum: number;

  /**
   * @generated from field: craig_stars.v1.WormholeStability stability = 4;
   */
  stability: WormholeStability;

  /**
   * @generated from field: int32 years_at_stability = 5;
   */
  yearsAtStability: number;

  /**
   * @generated from field: craig_stars.v1.WormholeSpec spec = 6;
   */
  spec?: WormholeSpec;
};

/**
 * @generated from message craig_stars.v1.Wormhole
 */
export type WormholeJson = {
  /**
   * @generated from field: craig_stars.v1.GameDBObject game_db_object = 1;
   */
  gameDbObject?: GameDBObjectJson;

  /**
   * @generated from field: craig_stars.v1.MapObject map_object = 2;
   */
  mapObject?: MapObjectJson;

  /**
   * @generated from field: int32 destination_num = 3;
   */
  destinationNum?: number;

  /**
   * @generated from field: craig_stars.v1.WormholeStability stability = 4;
   */
  stability?: WormholeStabilityJson;

  /**
   * @generated from field: int32 years_at_stability = 5;
   */
  yearsAtStability?: number;

  /**
   * @generated from field: craig_stars.v1.WormholeSpec spec = 6;
   */
  spec?: WormholeSpecJson;
};

/**
 * Describes the message craig_stars.v1.Wormhole.
 * Use `create(WormholeSchema)` to create a new message.
 */
export const WormholeSchema: GenMessage<Wormhole, {jsonType: WormholeJson}> = /*@__PURE__*/
  messageDesc(file_craig_stars_v1_wormhole, 0);

/**
 * @generated from message craig_stars.v1.WormholeSpec
 */
export type WormholeSpec = Message<"craig_stars.v1.WormholeSpec"> & {
  /**
   * @generated from field: craig_stars.v1.WormholeStats stats = 1;
   */
  stats?: WormholeStats;
};

/**
 * @generated from message craig_stars.v1.WormholeSpec
 */
export type WormholeSpecJson = {
  /**
   * @generated from field: craig_stars.v1.WormholeStats stats = 1;
   */
  stats?: WormholeStatsJson;
};

/**
 * Describes the message craig_stars.v1.WormholeSpec.
 * Use `create(WormholeSpecSchema)` to create a new message.
 */
export const WormholeSpecSchema: GenMessage<WormholeSpec, {jsonType: WormholeSpecJson}> = /*@__PURE__*/
  messageDesc(file_craig_stars_v1_wormhole, 1);

/**
 * @generated from message craig_stars.v1.WormholeStats
 */
export type WormholeStats = Message<"craig_stars.v1.WormholeStats"> & {
  /**
   * @generated from field: int32 years_to_degrade = 1;
   */
  yearsToDegrade: number;

  /**
   * @generated from field: double chance_to_jump = 2;
   */
  chanceToJump: number;

  /**
   * @generated from field: int32 jiggle_distance = 3;
   */
  jiggleDistance: number;
};

/**
 * @generated from message craig_stars.v1.WormholeStats
 */
export type WormholeStatsJson = {
  /**
   * @generated from field: int32 years_to_degrade = 1;
   */
  yearsToDegrade?: number;

  /**
   * @generated from field: double chance_to_jump = 2;
   */
  chanceToJump?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: int32 jiggle_distance = 3;
   */
  jiggleDistance?: number;
};

/**
 * Describes the message craig_stars.v1.WormholeStats.
 * Use `create(WormholeStatsSchema)` to create a new message.
 */
export const WormholeStatsSchema: GenMessage<WormholeStats, {jsonType: WormholeStatsJson}> = /*@__PURE__*/
  messageDesc(file_craig_stars_v1_wormhole, 2);

/**
 * @generated from enum craig_stars.v1.WormholeStability
 */
export enum WormholeStability {
  /**
   * @generated from enum value: WORMHOLE_STABILITY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: WORMHOLE_STABILITY_ROCK_SOLID = 1;
   */
  ROCK_SOLID = 1,

  /**
   * @generated from enum value: WORMHOLE_STABILITY_STABLE = 2;
   */
  STABLE = 2,

  /**
   * @generated from enum value: WORMHOLE_STABILITY_MOSTLY_STABLE = 3;
   */
  MOSTLY_STABLE = 3,

  /**
   * @generated from enum value: WORMHOLE_STABILITY_AVERAGE = 4;
   */
  AVERAGE = 4,

  /**
   * @generated from enum value: WORMHOLE_STABILITY_SLIGHTLY_VOLATILE = 5;
   */
  SLIGHTLY_VOLATILE = 5,

  /**
   * @generated from enum value: WORMHOLE_STABILITY_VOLATILE = 6;
   */
  VOLATILE = 6,

  /**
   * @generated from enum value: WORMHOLE_STABILITY_EXTREMELY_VOLATILE = 7;
   */
  EXTREMELY_VOLATILE = 7,
}

/**
 * @generated from enum craig_stars.v1.WormholeStability
 */
export type WormholeStabilityJson = "WORMHOLE_STABILITY_UNSPECIFIED" | "WORMHOLE_STABILITY_ROCK_SOLID" | "WORMHOLE_STABILITY_STABLE" | "WORMHOLE_STABILITY_MOSTLY_STABLE" | "WORMHOLE_STABILITY_AVERAGE" | "WORMHOLE_STABILITY_SLIGHTLY_VOLATILE" | "WORMHOLE_STABILITY_VOLATILE" | "WORMHOLE_STABILITY_EXTREMELY_VOLATILE";

/**
 * Describes the enum craig_stars.v1.WormholeStability.
 */
export const WormholeStabilitySchema: GenEnum<WormholeStability, WormholeStabilityJson> = /*@__PURE__*/
  enumDesc(file_craig_stars_v1_wormhole, 0);

