# Workflow to build & test on each commit or PR to develop
name: Build
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - "develop"

  push:
    branches:
      - "develop"

  workflow_dispatch: # allow manually triggering on drafts if need be

env:
  go-version: 1.24.x
  test_results: ./tmp/test-results

jobs:
  test_backend:
    # don't run job on draft PRs unless manually triggered
    if: ${{ github.event_name != 'pull-request' || github.event.pull_request.draft == 'false' }}
    name: Run backend Go tests
    strategy:
      matrix:
        os: [ubuntu-latest] # no need for multiple OSes if we're just running go tests
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      # build & test
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
          check-latest: true
          cache: true

      - name: Setup Mage
        uses: magefile/mage-action@v3
        with:
          install-only: true

      - name: Test Go Files
        id: go-tests
        run: |
          go run gotest.tools/gotestsum@latest \
          --format=github-actions \
          --format-hide-empty-pkg \
          --junitfile ${{env.test_results}}/go-test-report.xml \
          --junitfile-hide-empty-pkg
          --junitfile-project-name ${{github.repository}}
          --junitfile-testname-classname short
          --junitfile-testsuite-name short

      - name: Find and merge failing JSON diff files
        run: mage merge_temp_json
        if: always()

      - name: Upload JSON diffs to cloud
        uses: actions/upload-artifact@v4
        with:
          name: "JSON Diff"
          path: "./tmp/diff.json"
          if-no-files-found: ignore
          overwrite: true
          retention-days: 14
        if: always()

      - name: Produce Test Summary
        uses: test-summary/action@v2
        with:
          paths: ${{env.test_results}}/go-test-report.xml
        if: always()

  build:
    name: Build app and test frontend
    if: ${{ github.event_name != 'pull-request' || github.event.pull_request.draft == 'false' }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      # build the backend (fast)
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
          check-latest: true
          cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install Node.js dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Setup Mage
        uses: magefile/mage-action@v3
        with:
          install-only: true

      - name: Install tygo
        run: go install github.com/gzuidhof/tygo@v0.2.17
      - name: Install Node.js dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Generate Go files and frontend static resources
        run: mage generate

      - name: Grab images so tests don't complain
        run: mage images

      - name: Copy wasm_exec into frontend folder for the node build step
        run: mage copy_wasm_exec

      - name: Build Backend Go Binary
        run: CGO_ENABLED=1 GOARCH=amd64 GOOS=linux mage build_backend

        # build the frontend (slow)
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./frontend

      - name: Set Playwright env vars for logging
        run: echo "{PLAYWRIGHT_JUNIT_OUTPUT_NAME}={.${{env.test_results}}/playwright-report.xml}" >> $GITHUB_ENV

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ./frontend
        id: playwright-test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ${{env.test_results}}/playwright-report.xml
          retention-days: 1
        if: always()

      - name: Run Vitest tests
        run: npx vitest --run --outputFile.junit=.${{env.test_results}}/vitest-report.xml
        working-directory: ./frontend

      - name: Upload Vitest report
        uses: actions/upload-artifact@v4
        with:
          name: vitest-report
          path: ${{env.test_results}}/vitest-report.xml
          retention-days: 1
        if: always()

      - name: Build Frontend Binary
        run: npm run build
        working-directory: ./frontend

      - name: Produce Test Summary
        uses: test-summary/action@v2
        with:
          paths: "${{env.test_results}}/*_report.xml"
        if: always()
