# Workflow to build & test on each commit or PR to develop
name: Build
on:
  pull_request:
    branches:
      - "develop"
  push:
    branches:
      - "develop"

env:
  go-version: 1.23.x
  test_results: ./tmp/test-results

jobs:
  test_backend:
    name: Run backend Go tests
    # prevent workflow from running on forks
    strategy:
      matrix:
        os: [ubuntu-latest] # no need for multiple OSes if we're just running go tests
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      # build & test
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
          check-latest: true
          cache: true

      - name: Test Go Files
        id: go-tests
        run: go run gotest.tools/gotestsum@latest --format=github-actions --junitfile ${{env.test_results}}/go-test-report.xml --hide-summary=output --hide-empty-pkg
      - name: Produce Test Summary
        uses: test-summary/action@v2
        with:
          paths: ${{env.test_results}}/go-test-report.xml
          output: ${{env.test_results}}/go-test-summary.md
        if: always()

      - name: Upload Test Summary artifact
        uses: actions/upload-artifact@v4
        with:
          name: Go Test Summary
          path: ${{env.test_results}}/go-test-summary.md
          overwrite: true
          retention-days: 14
        if: always()

  bench_backend:
    name: Run backend Go benchmarks
    env:
      bench_time: 10 # 10s per bench run

    strategy:
      matrix:
        os: [ubuntu-latest] # no need for multiple OSes if we're just running benchmarks
    runs-on: ${{ matrix.os }}
    needs: test_backend
    # prevent workflow from running on forks
    cancel-timeout-minutes: 5 # if it takes more than 5 minutes we're in trouble
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
          check-latest: true
          cache: true

      - name: Run Go Benchmarks
        id: go-bench
        run: go run gotest.tools/gotestsum@latest --format=github-actions --junitfile ${{env.test_results}}/go-bench-report.xml --hide-summary=output --hide-empty-pkg -- -bench=. --benchmem --benchcount=10 --benchtime=${{env.bench_time}}

      - name: Produce Test Summary
        uses: test-summary/action@v2
        with:
          paths: ${{env.test_results}}/go-bench-report.xml
          output: ${{env.test_results}}/go-bench-summary.md
        if: always()

      - name: Upload benchmark summary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Go Benchmark Summary
          path: ${{env.test_results}}/go-bench-summary.md
          overwrite: true
          retention-days: 14
        if: always()

  build:
    name: Build app and test frontend
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: bench_backend
    # prevent workflow from running on forks

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      # build the backend (fast)
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
          check-latest: true
          cache: true

      - name: Build Go Binary
        run: CGO_ENABLED=1 GOARCH=amd64 GOOS=linux go build -ldflags='-s -w -extldflags "-static"' -o dist/craig-stars main.go

      - name: Build Wasm files
        run: make build_wasm

      # build the frontend (slow)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install Node.js dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./frontend

      - name: Set Playwright env vars for logging
        run: echo "{PLAYWRIGHT_JUNIT_OUTPUT_NAME}={${{env.test_results}}/playwright_report.xml}" >> $GITHUB_ENV

      - name: Run Playwright tests
        continue-on-error: true
        run: npx playwright test
        working-directory: ./frontend

      - name: Run Vitest tests
        continue-on-error: true
        run: npm run test --outputFile.junit=${{env.test_results}}/vitest_report.xml  
        working-directory: ./frontend

      - name: Build Frontend Binary
        if: success() 
        run: npm run build
        working-directory: ./frontend

      - name: Produce Test Summary
        uses: test-summary/action@v2
        with:
          paths: |
            ${{env.test_results}}/vitest-report.xml
            ${{env.test_results}}/playwright-report.xml

          output: ${{env.test_results}}/frontend-summary.md
        if: always()

      - name: Upload test summary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Frontend Test Summary
          path: ${{env.test_results}}/frontend-summary.md
          overwrite: true
          retention-days: 14
        if: always()
