# workflow to cut a new tag for each successful push to develop
name: Release
on:
  workflow_run:
    workflows: [Build]
    branches: [develop]
    types:
      - completed

jobs:
  # cut a new tag
  tag:
    name: Bump version number
    # tasks only run on head repo by default (not forks); change this to enable it
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.repository == 'sirgwain/craig-stars' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: "patch"
          BRANCH_HISTORY: "last"
    outputs:
      version: ${{ steps.bump.outputs.new_tag }}

  build:
    if: github.repository == 'sirgwain/craig-stars'
    strategy:
      matrix:
        go-version: [1.25.x]
        tinygo-version: [0.39.0]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: tag
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      # get some build metadata we can put in the binary and package.json
      - name: Get build time
        id: buildTime
        run: echo "buildTime=`date +'%y.%m.%d %H:%M:%S'`" >> $GITHUB_OUTPUT

      #  setup build environment
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache: true
      - name: Setup tinygo
        uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: ${{ matrix.tinygo-version }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Setup Mage
        uses: magefile/mage-action@v3
        with:
          install-only: true

      - name: Install Node.js dependencies
        run: npm ci
        working-directory: ./frontend

      # generate the backend go files needed for release
      - name: Build a CI version of the backend with version/build time
        run: |
          CGO_ENABLED=1 GOARCH=amd64 GOOS=linux \
          mage build_backend_ci "${{ needs.tag.outputs.version }}" "${GITHUB_SHA}" "${{ steps.buildTime.outputs.buildTime }}"
      - name: Tar up the binary for publish
        run: tar -cvf ./dist/craig-stars.tgz -C ./dist ./craig-stars
      - name: Copy wasm_exec into frontend folder for the node build step
        run: mage copy_wasm_exec_tinygo

      # set the version in package.json and build the frontend
      - run: jq ".version = \"${{ needs.tag.outputs.version }}\"" package.json > package.json.tmp && mv package.json.tmp package.json
        working-directory: ./frontend
      - run: npm run build
        working-directory: ./frontend
      - run: mkdir -p dist/
      - run: tar -cvf ./dist/frontend.tgz -C frontend/build .

      # upload the dist folder to github's artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: ./dist/*.tgz
          retention-days: 1

  release:
    if: github.repository == 'sirgwain/craig-stars'
    runs-on: ubuntu-latest
    name: Create release
    needs: [build, tag]
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-artifacts
          path: dist-artifacts

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Published ${{ needs.tag.outputs.version }}
          tag: ${{ needs.tag.outputs.version }}
          artifacts: ./dist-artifacts/*.tgz
          artifactContentType: application/zip
          generateReleaseNotes: true

  deploy:
    if: github.repository == 'sirgwain/craig-stars'
    name: Deploy to server
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - run: gh workflow run --repo sirgwain/craig-stars-ops deploy.yml
        env:
          GH_TOKEN: ${{ secrets.CRAIG_STARS_OPS_DEPLOY }}
